<?php

return array(
    'home-hero-eyebrow' => 'Agence web à Nantes',
    'home-hero-title' => 'Agence web à Nantes — sites WordPress & CRM sur mesure',
    'home-hero-text' => 'Location dès 350€/mois sans investissement initial · Maquette gratuite en 48h · SEO intégré · Zéro frais de création.',
    'home-hero-cta-primary' => array(
        'title' => 'Demander ma maquette gratuite',
        'url' => '#contact',
        'target' => '',
    ),
    'home-hero-cta-secondary' => array(
        'title' => 'Découvrir la location dès 350€/mois',
        'url' => '#tarifs',
        'target' => '',
    ),
    'home-hero-stats' => array(
        array('value' => '350€/mois', 'label' => 'Tout inclus'),
        array('value' => '48h', 'label' => 'Maquette gratuite'),
        array('value' => '9+', 'label' => 'Projets réalisés'),
    ),
    'home-trust-label' => 'Ils nous font confiance',
    'home-services-eyebrow' => 'Nos services',
    'home-services-title' => 'Des solutions web sur mesure pour développer votre activité',
    'home-services-link' => array(
        'title' => 'Voir tous nos services',
        'url' => '#',
        'target' => '',
    ),
    'home-services-items' => array(
        array(
            'title' => 'Création de site internet',
            'text' => 'Site WordPress sur mesure, optimisé SEO et pensé pour convertir vos visiteurs en clients.',
            'url' => '#',
        ),
        array(
            'title' => 'CRM sur mesure',
            'text' => 'Connectez votre site à un CRM adapté à votre métier. Fini Excel, fini les leads perdus.',
            'url' => '#',
        ),
        array(
            'title' => 'Location de site internet',
            'text' => 'Site professionnel dès 350€/mois : création, hébergement, maintenance. Zéro frais de création.',
            'url' => '#tarifs',
        ),
        array(
            'title' => 'Refonte WordPress',
            'text' => 'Modernisez votre site sans perdre votre référencement. Audit, migration et optimisation SEO.',
            'url' => '#',
        ),
        array(
            'title' => 'Site e-commerce WooCommerce',
            'text' => 'Boutique en ligne performante avec paiement sécurisé, gestion des stocks et SEO produits.',
            'url' => '#',
        ),
        array(
            'title' => 'Maintenance WordPress',
            'text' => 'Mises à jour, sauvegardes, sécurité et support réactif pour un site toujours opérationnel.',
            'url' => '#',
        ),
    ),
    'home-why-eyebrow' => 'Pourquoi Crescendo à Nantes ?',
    'home-why-items' => array(
        array('text' => 'Agence locale nantaise, réactive et disponible'),
        array('text' => 'WordPress sur mesure, pas de templates génériques'),
        array('text' => 'SEO intégré dès la conception du site'),
        array('text' => 'Tarifs transparents : location dès 350€/mois'),
        array('text' => 'Accompagnement de A à Z : stratégie, design, dev, suivi'),
    ),
    'home-why-projects' => array(
        array('title' => 'Ludovic Géhéniaux', 'category' => 'Coloriste', 'has_crm' => false),
        array('title' => 'Maison Jaden', 'category' => 'Constructeur', 'has_crm' => true),
        array('title' => 'Be Focus', 'category' => 'Formation', 'has_crm' => true),
        array('title' => 'Atelier Gambetta', 'category' => 'Branding', 'has_crm' => true),
        array('title' => 'Ta Kifé', 'category' => 'E-commerce', 'has_crm' => false),
        array('title' => 'CM&A Associés', 'category' => 'Avocats', 'has_crm' => false),
        array('title' => 'Frénésie', 'category' => 'Agence créative', 'has_crm' => false),
        array('title' => 'Padam Immo', 'category' => 'Immobilier', 'has_crm' => false),
        array('title' => 'Car Design', 'category' => 'Automobile', 'has_crm' => false),
    ),
    'home-method-eyebrow' => 'Notre méthode',
    'home-method-title' => 'Un accompagnement en 5 étapes',
    'home-method-steps' => array(
        array('title' => 'Stratégie', 'text' => 'Analyse de vos objectifs, de votre cible et de votre positionnement digital.'),
        array('title' => 'Design', 'text' => 'Maquette gratuite sous 48h pour valider la direction créative.'),
        array('title' => 'Développement', 'text' => 'Intégration WordPress sur mesure, optimisée performance et SEO.'),
        array('title' => 'Lancement', 'text' => 'Mise en ligne, tests, formation et indexation Google.'),
        array('title' => 'Suivi', 'text' => 'Maintenance, évolutions et optimisation continue de votre site.'),
    ),
    'home-pricing-eyebrow' => 'Tarifs transparents',
    'home-pricing-title' => 'Location ou achat ? À vous de choisir.',
    'home-pricing-location-price' => '350€',
    'home-pricing-location-features' => array(
        array('text' => 'Création sur mesure incluse'),
        array('text' => 'Hébergement premium'),
        array('text' => 'Maintenance & mises à jour'),
        array('text' => 'SEO de base intégré'),
        array('text' => 'Support réactif'),
        array('text' => 'Zéro frais de création'),
    ),
    'home-pricing-location-cta' => array(
        'title' => 'Choisir la location',
        'url' => '#contact',
        'target' => '',
    ),
    'home-pricing-table' => array(
        array('label' => 'Investissement initial', 'location' => '0€', 'achat' => '3 000 – 8 000€'),
        array('label' => 'Coût sur 5 ans', 'location' => '~21 000€', 'achat' => '~25 000€+'),
        array('label' => 'Maintenance', 'location' => 'Incluse', 'achat' => '150–250€/mois'),
        array('label' => 'SEO', 'location' => 'Inclus', 'achat' => 'Sur devis'),
        array('label' => 'Évolutivité', 'location' => 'Incluse', 'achat' => 'Sur devis'),
    ),
    'home-crm-eyebrow' => 'Nouveau pilier',
    'home-crm-title' => 'CRM sur mesure',
    'home-crm-subtitle' => 'Le lien entre votre site et votre croissance.',
    'home-crm-text' => 'Nous connectons votre site WordPress à un CRM adapté à votre process commercial. Leads captés, suivis et convertis — sans Excel ni outils déconnectés.',
    'home-crm-list' => array(
        array('text' => 'Connexion native site web ↔ CRM'),
        array('text' => 'Adapté à votre métier et vos process'),
        array('text' => 'HubSpot, Pipedrive ou solution 100% sur mesure'),
        array('text' => 'Formation de votre équipe incluse'),
    ),
    'home-crm-cta' => array(
        'title' => 'Découvrir le CRM',
        'url' => '#',
        'target' => '',
    ),
    'home-testimonials-eyebrow' => 'Nos clients parlent de nous',
    'home-testimonials-items' => array(
        array(
            'quote' => 'Crescendo a transformé notre présence en ligne. Le site génère des leads qualifiés chaque semaine.',
            'name' => 'Julien M.',
            'company' => 'Maison Jaden',
            'rating' => 5,
        ),
        array(
            'quote' => 'Professionnels, réactifs et transparents sur les tarifs. La location à 350€/mois était parfaite pour nous.',
            'name' => 'Sophie L.',
            'company' => 'Be Focus',
            'rating' => 5,
        ),
        array(
            'quote' => 'Le CRM connecté à notre site a changé notre façon de gérer les prospects. Un vrai gain de temps.',
            'name' => 'Thomas R.',
            'company' => 'Atelier Gambetta',
            'rating' => 5,
        ),
    ),
    'home-cta-title' => 'Prêt à démarrer votre projet ?',
    'home-cta-text' => 'Demandez votre maquette gratuite en 48h.',
    'home-cta-button' => array(
        'title' => 'Demander ma maquette gratuite',
        'url' => '#contact',
        'target' => '',
    ),
    'home-faq-items' => array(
        array(
            'question' => 'Qu\'est-ce qui est inclus dans l\'offre à 350€/mois ?',
            'answer' => 'Création du site sur mesure, hébergement premium, maintenance, mises à jour, sauvegardes, SEO de base et support réactif. Aucun frais de création.',
        ),
        array(
            'question' => 'La maquette est-elle vraiment gratuite ?',
            'answer' => 'Oui, nous livrons une maquette personnalisée sous 48h, sans engagement, pour valider la direction créative avant tout projet.',
        ),
        array(
            'question' => 'Combien de temps pour mettre en ligne mon site ?',
            'answer' => 'Un site vitrine professionnel est livré en 4 à 6 semaines après validation de la maquette.',
        ),
        array(
            'question' => 'Proposez-vous aussi des CRM ?',
            'answer' => 'Oui, nous développons des CRM sur mesure connectés à votre site WordPress, ou intégrons HubSpot et Pipedrive selon vos besoins.',
        ),
        array(
            'question' => 'Intervenez-vous uniquement à Nantes ?',
            'answer' => 'Nous sommes basés à Nantes et intervenons sur toute la Loire-Atlantique : Saint-Herblain, Rezé, Orvault, Carquefou et environs.',
        ),
    ),
    'home-contact-title' => 'Discutons de votre projet',
);
