#!/usr/bin/env python3
"""Generate missing money service page JSON imports."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
BASE = "https://crescendo-studio.io"

PAGES = [
    {
        "file": "agence-web-nantes.json",
        "page": {
            "title": "Agence web à Nantes",
            "slug": "agence-web-nantes",
            "menu_order": 5,
        },
        "seo": {
            "meta_title": "Agence web Nantes — WordPress sur mesure dès 350€/mois | Crescendo",
            "meta_description": "Agence web à Nantes : création, refonte et location de sites WordPress sur mesure. SEO intégré, maquette gratuite 48h. TPE, PME et professions libérales.",
            "focus_keyword": "agence web nantes",
            "canonical": f"{BASE}/agence-web-nantes/",
        },
        "fields": {
            "service-hero-eyebrow": "Agence web · Nantes",
            "service-hero-title": "Agence web à Nantes",
            "service-hero-intro": "Crescendo Studio est une agence web nantaise spécialisée WordPress sur mesure. Nous accompagnons les TPE, PME et professions libérales de Loire-Atlantique — création, refonte, SEO et location dès 350 €/mois, sans template générique ni surprise budgétaire.",
            "service-hero-cta-primary": {"title": "Demander ma maquette gratuite", "url": "#contact", "target": ""},
            "service-hero-cta-secondary": {"title": "Voir nos réalisations", "url": "/realisations/", "target": ""},
            "service-hero-note": "Maquette gratuite en 48h · Agence locale",
            "service-benefits": [
                {"title": "WordPress 100 % sur mesure", "text": "Design, développement et SEO pensés pour votre activité — pas de thème préfabriqué."},
                {"title": "Location sans investissement", "text": "Site professionnel dès 350 €/mois, création et maintenance incluses."},
                {"title": "SEO intégré dès le départ", "text": "Structure, performances et contenu calibrés pour Google dès la conception."},
                {"title": "Accompagnement de proximité", "text": "Rendez-vous à Nantes, visio ou sur votre site — réactivité garantie."},
            ],
            "service-included-eyebrow": "Notre accompagnement",
            "service-included-title": "Ce que couvre une collaboration avec Crescendo",
            "service-included-text": "De la stratégie digitale à la mise en ligne, nous pilotons l'ensemble du projet : UX/UI, développement WordPress, référencement, formation et maintenance.",
            "service-included-price": "350€",
            "service-included-price-suffix": "/mois en location",
            "service-included-cta": {"title": "Parler de mon projet", "url": "#contact", "target": ""},
            "service-included-features": [
                {"text": "Audit et cadrage stratégique"},
                {"text": "Maquette gratuite sous 48 h"},
                {"text": "Développement WordPress sur mesure"},
                {"text": "Optimisation SEO technique et éditoriale"},
                {"text": "Hébergement premium et sauvegardes"},
                {"text": "Maintenance, sécurité et évolutions"},
                {"text": "Formation à l'administration du site"},
                {"text": "Support réactif par l'équipe nantaise"},
            ],
            "service-compare-eyebrow": "Agence vs freelance vs DIY",
            "service-compare-title": "Pourquoi travailler avec une agence web à Nantes ?",
            "service-compare-text": "Un freelance isolé ou un constructeur type Wix ne couvre pas toujours le design, le développement, le SEO et la maintenance. Une agence structurée sécurise la qualité et la durabilité de votre investissement.",
            "service-compare-cta": {"title": "Demander un premier échange", "url": "#contact", "target": ""},
            "service-compare-col1-label": "Agence Crescendo",
            "service-compare-col2-label": "Freelance / DIY",
            "service-compare-table": [
                {"label": "Design sur mesure", "col1": "✓", "col2": "Variable"},
                {"label": "SEO dès la conception", "col1": "✓", "col2": "Rarement"},
                {"label": "Maintenance incluse", "col1": "✓ (location)", "col2": "Sur devis"},
                {"label": "Évolutivité WordPress", "col1": "✓", "col2": "Limitée (DIY)"},
                {"label": "Interlocuteur unique", "col1": "✓", "col2": "Multi-prestataires"},
                {"label": "Délai moyen vitrine", "col1": "4–6 semaines", "col2": "Imprévisible"},
            ],
            "service-compare-note": "Un partenaire unique pour créer, référencer et faire évoluer votre site",
            "service-audience-eyebrow": "Nos clients à Nantes",
            "service-audience-title": "Une agence adaptée à chaque profil d'entreprise.",
            "service-audience-cards": [
                {"title": "Artisans & BTP", "text": "Sites vitrine orientés devis et SEO local.", "url": "/creation-site-artisan-nantes/"},
                {"title": "Professions libérales", "text": "Image premium, prise de RDV, conformité déontologique.", "url": "/creation-site-avocat-nantes/"},
                {"title": "PME & industrie", "text": "Sites B2B, catalogues, connexion CRM.", "url": "/creation-site-web-nantes/"},
                {"title": "Commerces & restauration", "text": "Carte, réservation, visibilité locale.", "url": "/creation-site-restaurant-nantes/"},
            ],
            "service-projects-eyebrow": "Réalisations nantaises",
            "service-projects-title": "Des sites livrés pour des secteurs exigeants.",
            "service-projects": [
                {"title": "Maison Jaden", "category": "Construction", "tags": "WordPress · CRM · SEO", "url": "/realisations/maison-jaden/"},
                {"title": "Gide", "category": "Cabinet d'avocats", "tags": "WordPress · Multilingue", "url": "/realisations/gide/"},
                {"title": "Padam Immo", "category": "Immobilier", "tags": "WordPress · SEO local", "url": "/realisations/padam-immo/"},
            ],
            "service-method-eyebrow": "Notre méthode",
            "service-method-title": "Un projet web cadré, de la maquette au suivi mensuel.",
            "service-method-steps": [
                {"title": "Échange & cadrage", "text": "Compréhension de vos objectifs, cibles et contraintes budgétaires."},
                {"title": "Maquette 48h", "text": "Direction créative gratuite pour valider le design avant développement."},
                {"title": "Développement", "text": "Intégration WordPress sur mesure, optimisée SEO et mobile."},
                {"title": "Recette & lancement", "text": "Tests, indexation Google, formation à l'administration."},
                {"title": "Suivi continu", "text": "Maintenance, évolutions et optimisation des performances."},
            ],
            "service-faq-eyebrow": "Questions fréquentes",
            "service-faq-title": "Tout savoir sur notre agence web à Nantes.",
            "service-faq-items": [
                {"question": "Pourquoi choisir une agence web locale à Nantes ?", "answer": "La proximité facilite les ateliers contenu, les rendez-vous de cadrage et la compréhension de votre marché nantais. Nous intervenons aussi en visio sur toute la Loire-Atlantique."},
                {"question": "Proposez-vous la location de site internet ?", "answer": "Oui, dès 350 €/mois tout inclus : création, hébergement, maintenance et SEO de base. Idéal pour lisser le budget sans frais de setup."},
                {"question": "Quelle est la différence avec un freelance ?", "answer": "Nous réunissons design, développement, SEO et maintenance dans une équipe structurée. Vous avez un interlocuteur unique et une continuité de service garantie."},
                {"question": "Combien coûte un site web à Nantes ?", "answer": "En location : 350 €/mois sans frais de création. En achat sur mesure : de 3 000 à 8 000 € selon le périmètre (pages, fonctionnalités, multilingue)."},
                {"question": "Quels délais pour la mise en ligne ?", "answer": "4 à 6 semaines pour un site vitrine après validation de la maquette. Les projets plus complexes (e-commerce, CRM) demandent 8 à 12 semaines."},
                {"question": "Intervenez-vous hors de Nantes ?", "answer": "Oui, sur toute la Loire-Atlantique : Saint-Nazaire, Saint-Herblain, Rezé, Carquefou et au-delà."},
                {"question": "Travaillez-vous au forfait ou en régie ?", "answer": "Nos projets web sont au forfait ou en abonnement mensuel (location). Le CRM sur mesure est chiffré après audit."},
                {"question": "Puis-je voir des exemples de sites réalisés ?", "answer": "Oui, consultez notre portfolio : constructeurs, cabinets, immobilier, formation. Chaque projet est WordPress sur mesure."},
            ],
            "service-final-cta-title": "Prêt à travailler avec une agence web nantaise exigeante ?",
            "service-final-reassurance": [
                {"text": "Maquette gratuite en 48h"},
                {"text": "WordPress 100 % sur mesure"},
                {"text": "Agence basée à Nantes"},
            ],
        },
    },
    {
        "file": "creation-site-web-nantes.json",
        "page": {
            "title": "Création de site internet à Nantes",
            "slug": "creation-site-web-nantes",
            "menu_order": 6,
        },
        "seo": {
            "meta_title": "Création site internet Nantes — WordPress sur mesure | Crescendo",
            "meta_description": "Création de site internet à Nantes pour TPE et PME : WordPress sur mesure, SEO local, design premium. Maquette gratuite 48h. Location dès 350€/mois.",
            "focus_keyword": "création site internet nantes",
            "canonical": f"{BASE}/creation-site-web-nantes/",
        },
        "fields": {
            "service-hero-eyebrow": "Création site web · Nantes",
            "service-hero-title": "Création de site internet à Nantes",
            "service-hero-intro": "Vous lancez une activité ou modernisez votre présence en ligne ? Nous créons des sites internet WordPress sur mesure pour les entreprises nantaises : design premium, parcours orienté conversion, SEO local intégré — en location dès 350 €/mois ou en achat clé en main.",
            "service-hero-cta-primary": {"title": "Demander ma maquette gratuite", "url": "#contact", "target": ""},
            "service-hero-cta-secondary": {"title": "Comparer location et achat", "url": "/location-site-internet/", "target": ""},
            "service-hero-note": "Site vitrine livré en 4 à 6 semaines",
            "service-benefits": [
                {"title": "Site orienté business", "text": "Chaque page sert un objectif : crédibilité, leads, prise de RDV ou vente."},
                {"title": "Mobile first", "text": "70 % des recherches locales se font sur smartphone — votre site en est optimisé."},
                {"title": "SEO local Nantes", "text": "Structure et contenu pensés pour « votre métier + Nantes »."},
                {"title": "Budget maîtrisé", "text": "Location sans frais de création ou achat chiffré au forfait."},
            ],
            "service-included-eyebrow": "Création clé en main",
            "service-included-title": "Ce qui est inclus dans votre site internet",
            "service-included-text": "Un site professionnel complet : stratégie, design UX/UI, développement WordPress, rédaction SEO, hébergement et formation.",
            "service-included-price": "350€",
            "service-included-price-suffix": "/mois (location)",
            "service-included-cta": {"title": "Obtenir ma maquette gratuite", "url": "#contact", "target": ""},
            "service-included-features": [
                {"text": "Cadrage et arborescence SEO"},
                {"text": "Design UX/UI personnalisé"},
                {"text": "Développement WordPress sur mesure"},
                {"text": "Pages services et zone géographique"},
                {"text": "Formulaire de contact ou devis"},
                {"text": "Optimisation Core Web Vitals"},
                {"text": "Google Analytics & Search Console"},
                {"text": "Formation à la gestion du contenu"},
            ],
            "service-compare-eyebrow": "Location vs achat",
            "service-compare-title": "Comment financer la création de votre site à Nantes ?",
            "service-compare-text": "La location lisse votre trésorerie. L'achat convient si vous disposez d'un budget initial et d'une équipe marketing interne.",
            "service-compare-cta": {"title": "Choisir la location 350€/mois", "url": "/location-site-internet/", "target": ""},
            "service-compare-col1-label": "Location 350€/mois",
            "service-compare-col2-label": "Achat sur mesure",
            "service-compare-table": [
                {"label": "Investissement initial", "col1": "0€", "col2": "3 000 – 8 000€"},
                {"label": "Création incluse", "col1": "✓", "col2": "✓"},
                {"label": "Maintenance", "col1": "Incluse", "col2": "150–250€/mois"},
                {"label": "Évolutions", "col1": "Incluses (mineures)", "col2": "Sur devis"},
                {"label": "Propriété du site", "col1": "Location", "col2": "Vous"},
                {"label": "Idéal pour", "col1": "TPE, lancement", "col2": "PME établies"},
            ],
            "service-compare-note": "Les deux formules incluent WordPress sur mesure — pas de template générique",
            "service-audience-eyebrow": "Types de sites",
            "service-audience-title": "Quel site internet pour votre activité ?",
            "service-audience-cards": [
                {"title": "Site vitrine", "text": "Présentation services, réalisations, équipe.", "url": "/creation-site-vitrine-nantes/"},
                {"title": "Site WordPress", "text": "Plateforme évolutive, blog, multilingue.", "url": "/creation-site-wordpress/"},
                {"title": "Site e-commerce", "text": "Vente en ligne WooCommerce sur mesure.", "url": "/creation-site-ecommerce-nantes/"},
                {"title": "Refonte", "text": "Moderniser un site existant sans perdre le SEO.", "url": "/refonte-site-wordpress/"},
            ],
            "service-projects-eyebrow": "Exemples de créations",
            "service-projects-title": "Des sites internet livrés à Nantes et en Loire-Atlantique.",
            "service-projects": [
                {"title": "Be Focus", "category": "Formation", "tags": "WordPress · Booking", "url": "/realisations/be-focus/"},
                {"title": "Bag X Pro", "category": "Industrie B2B", "tags": "WordPress · Catalogue", "url": "/realisations/bag-x-pro/"},
                {"title": "Ludovic Géhéniaux", "category": "Artisan", "tags": "WordPress · Réservation", "url": "/realisations/ludovic-geheniaux/"},
            ],
            "service-method-eyebrow": "Notre process",
            "service-method-title": "De l'idée au site en ligne en 5 étapes.",
            "service-method-steps": [
                {"title": "Brief & stratégie", "text": "Objectifs, cibles, mots-clés et arborescence validés ensemble."},
                {"title": "Maquette 48h", "text": "Prototype visuel gratuit pour valider la direction."},
                {"title": "Contenus & design", "text": "Rédaction SEO, visuels et ajustements collaboratifs."},
                {"title": "Développement", "text": "Intégration WordPress, formulaires, tracking."},
                {"title": "Lancement", "text": "Mise en ligne, indexation, formation et suivi."},
            ],
            "service-faq-eyebrow": "FAQ",
            "service-faq-title": "Questions sur la création de site internet à Nantes.",
            "service-faq-items": [
                {"question": "Combien coûte la création d'un site internet à Nantes ?", "answer": "En location : 350 €/mois sans frais de création. En achat : entre 3 000 et 8 000 € selon le nombre de pages et fonctionnalités."},
                {"question": "Quelle technologie utilisez-vous ?", "answer": "WordPress sur mesure — le CMS le plus répandu au monde, flexible, sécurisé et facile à administrer."},
                {"question": "Mon site sera-t-il visible sur Google à Nantes ?", "answer": "Oui. SEO technique, contenu géolocalisé, schema.org et fiche Google Business Profile font partie de notre méthode."},
                {"question": "Puis-je modifier mon site moi-même ?", "answer": "Oui. L'interface d'administration est adaptée à vos contenus : textes, images, actualités, sans toucher au code."},
                {"question": "Quelle différence entre site vitrine et site e-commerce ?", "answer": "Le vitrine génère des contacts. L'e-commerce intègre un catalogue, un panier et un paiement en ligne via WooCommerce."},
                {"question": "Proposez-vous la rédaction des contenus ?", "answer": "Oui, en option ou inclus selon la formule. Nous rédigeons des textes optimisés SEO orientés conversion."},
                {"question": "Combien de temps pour créer mon site ?", "answer": "4 à 6 semaines pour un vitrine standard. E-commerce ou multilingue : 8 à 12 semaines."},
                {"question": "Que se passe-t-il après la mise en ligne ?", "answer": "Maintenance, mises à jour de sécurité, sauvegardes et évolutions — incluses en location ou via contrat dédié."},
            ],
            "service-final-cta-title": "Lancez la création de votre site internet à Nantes",
            "service-final-reassurance": [
                {"text": "Maquette gratuite en 48h"},
                {"text": "Location dès 350€/mois"},
                {"text": "SEO local intégré"},
            ],
        },
    },
    {
        "file": "refonte-site-wordpress.json",
        "page": {
            "title": "Refonte de site WordPress à Nantes",
            "slug": "refonte-site-wordpress",
            "menu_order": 12,
        },
        "seo": {
            "meta_title": "Refonte site WordPress Nantes — Sans perdre votre SEO | Crescendo",
            "meta_description": "Refonte de site WordPress à Nantes : design moderne, performances, SEO préservé. Audit gratuit, migration sécurisée, maquette 48h. Agence WordPress locale.",
            "focus_keyword": "refonte site wordpress nantes",
            "canonical": f"{BASE}/refonte-site-wordpress/",
        },
        "fields": {
            "service-hero-eyebrow": "Refonte WordPress · Nantes",
            "service-hero-title": "Refonte de site WordPress à Nantes",
            "service-hero-intro": "Votre site WordPress est lent, daté ou non responsive ? Nous refondons votre plateforme sans sacrifier votre référencement : audit technique, conservation des URLs performantes, design sur mesure et migration sécurisée vers un WordPress moderne.",
            "service-hero-cta-primary": {"title": "Demander un audit gratuit", "url": "#contact", "target": ""},
            "service-hero-cta-secondary": {"title": "Voir une refonte réalisée", "url": "/realisations/gide/", "target": ""},
            "service-hero-note": "Audit et recommandations sous 48h",
            "service-benefits": [
                {"title": "SEO préservé", "text": "Redirections 301, conservation des pages indexées, audit des positions."},
                {"title": "Performances x2", "text": "Code allégé, Core Web Vitals optimisés, temps de chargement réduit."},
                {"title": "Design actuel", "text": "Image de marque modernisée, parcours utilisateur repensé."},
                {"title": "Admin simplifiée", "text": "Interface claire pour que vos équipes gèrent le contenu sans friction."},
            ],
            "service-included-eyebrow": "Refonte complète",
            "service-included-title": "Ce que comprend une refonte WordPress",
            "service-included-text": "Nous ne posons pas un thème par-dessus l'ancien site : nous reconstruisons proprement en capitalisant sur ce qui fonctionne déjà.",
            "service-included-price": "Sur devis",
            "service-included-price-suffix": "",
            "service-included-cta": {"title": "Obtenir mon audit", "url": "#contact", "target": ""},
            "service-included-features": [
                {"text": "Audit technique, SEO et UX"},
                {"text": "Inventaire des contenus et URLs"},
                {"text": "Nouveau design UX/UI sur mesure"},
                {"text": "Développement WordPress propre"},
                {"text": "Plan de redirections 301"},
                {"text": "Migration des contenus et médias"},
                {"text": "Tests multi-navigateurs et mobile"},
                {"text": "Formation et documentation"},
            ],
            "service-compare-eyebrow": "Refonte vs patch",
            "service-compare-title": "Refondre ou rafistoler : que choisir ?",
            "service-compare-text": "Empiler des plugins et des correctifs sur un site vieillissant coûte plus cher à moyen terme qu'une refonte structurée — surtout si votre SEO en souffre.",
            "service-compare-cta": {"title": "Planifier ma refonte", "url": "#contact", "target": ""},
            "service-compare-col1-label": "Refonte sur mesure",
            "service-compare-col2-label": "Correctifs ponctuels",
            "service-compare-table": [
                {"label": "Performances", "col1": "Optimisées dès le départ", "col2": "Dégradation continue"},
                {"label": "SEO", "col1": "Migré proprement", "col2": "Risque de casse"},
                {"label": "Design", "col1": "Cohérent et moderne", "col2": "Patchwork visuel"},
                {"label": "Sécurité", "col1": "Code à jour", "col2": "Failles accumulées"},
                {"label": "Coût sur 3 ans", "col1": "Maîtrisé", "col2": "Souvent supérieur"},
                {"label": "Évolutivité", "col1": "✓", "col2": "Limitée"},
            ],
            "service-compare-note": "Une refonte bien menée améliore SEO et conversion simultanément",
            "service-audience-eyebrow": "Situations fréquentes",
            "service-audience-title": "Quand refondre son site WordPress ?",
            "service-audience-cards": [
                {"title": "Site non responsive", "text": "Conçu avant le mobile — pénalisé par Google.", "url": "/refonte-site-wordpress/"},
                {"title": "Chute de trafic SEO", "text": "Positions perdues, contenu obsolète.", "url": "/agence-seo-nantes/"},
                {"title": "Changement de marque", "text": "Fusion, repositionnement, nouvelle identité.", "url": "/creation-site-wordpress/"},
                {"title": "Site lent ou piraté", "text": "Plugins obsolètes, failles de sécurité.", "url": "/maintenance-wordpress/"},
            ],
            "service-projects-eyebrow": "Refontes livrées",
            "service-projects-title": "Des sites modernisés sans rupture SEO.",
            "service-projects": [
                {"title": "Gide", "category": "Cabinet international", "tags": "Refonte · Multilingue · API", "url": "/realisations/gide/"},
                {"title": "Padam Immo", "category": "Immobilier", "tags": "Refonte · SEO local", "url": "/realisations/padam-immo/"},
                {"title": "Maison Jaden", "category": "Construction", "tags": "WordPress · CRM", "url": "/realisations/maison-jaden/"},
            ],
            "service-method-eyebrow": "Méthode refonte",
            "service-method-title": "5 étapes pour refondre sans perdre vos acquis.",
            "service-method-steps": [
                {"title": "Audit", "text": "Analyse SEO, technique, contenus et parcours utilisateur."},
                {"title": "Stratégie", "text": "Arbitrage conserver / fusionner / supprimer les pages."},
                {"title": "Design & contenu", "text": "Maquette, réécriture SEO, validation métier."},
                {"title": "Développement", "text": "Nouveau WordPress, redirections, tests de charge."},
                {"title": "Bascule", "text": "Mise en production planifiée, monitoring post-lancement."},
            ],
            "service-faq-eyebrow": "FAQ refonte",
            "service-faq-title": "Questions sur la refonte WordPress à Nantes.",
            "service-faq-items": [
                {"question": "Vais-je perdre mon référencement Google ?", "answer": "Non si la refonte est bien menée. Nous cartographions vos URLs, mettons en place des redirections 301 et surveillons Search Console après la bascule."},
                {"question": "Combien coûte une refonte de site WordPress ?", "answer": "Entre 4 000 et 12 000 € selon le volume de pages, les langues, les intégrations et le niveau de personnalisation. Devis après audit."},
                {"question": "Quelle durée pour une refonte complète ?", "answer": "8 à 14 semaines en moyenne : audit (1 sem), design (2–3 sem), développement (3–5 sem), recette et bascule (1–2 sem)."},
                {"question": "Mon site actuel est-il WordPress obligatoirement ?", "answer": "Non. Nous migrons aussi depuis d'autres CMS (Wix, Joomla, HTML statique) vers WordPress sur mesure."},
                {"question": "Puis-je garder mes contenus existants ?", "answer": "Oui. Nous migrons textes, images et structure. Les contenus faibles sont réécrits pour le SEO."},
                {"question": "Travaillez-vous sur des sites e-commerce ?", "answer": "Oui, refonte WooCommerce incluse : produits, catégories, historique de commandes selon faisabilité."},
                {"question": "Assurez-vous la maintenance après refonte ?", "answer": "Oui, via contrat maintenance ou formule location 350 €/mois."},
                {"question": "Proposez-vous un audit avant de refondre ?", "answer": "Oui, audit gratuit avec recommandations chiffrées sous 48 h après premier échange."},
            ],
            "service-final-cta-title": "Modernisez votre site WordPress sans repartir de zéro",
            "service-final-reassurance": [
                {"text": "Audit gratuit"},
                {"text": "SEO préservé"},
                {"text": "Agence WordPress Nantes"},
            ],
        },
    },
    {
        "file": "creation-site-ecommerce-nantes.json",
        "page": {
            "title": "Création de site e-commerce à Nantes",
            "slug": "creation-site-ecommerce-nantes",
            "menu_order": 13,
        },
        "seo": {
            "meta_title": "Création site e-commerce Nantes — WooCommerce sur mesure | Crescendo",
            "meta_description": "Création de site e-commerce à Nantes : WooCommerce sur mesure, paiement sécurisé, SEO produits, design premium. Boutique en ligne performante. Devis gratuit.",
            "focus_keyword": "création site e-commerce nantes",
            "canonical": f"{BASE}/creation-site-ecommerce-nantes/",
        },
        "fields": {
            "service-hero-eyebrow": "E-commerce · Nantes",
            "service-hero-title": "Création de site e-commerce à Nantes",
            "service-hero-intro": "Vendez en ligne avec une boutique WooCommerce sur mesure : catalogue produits, tunnel d'achat optimisé, paiement sécurisé et SEO produits intégré. Nous créons des sites e-commerce performants pour les marques et commerçants nantais — sans Shopify ni template générique.",
            "service-hero-cta-primary": {"title": "Demander un devis e-commerce", "url": "#contact", "target": ""},
            "service-hero-cta-secondary": {"title": "Voir nos réalisations", "url": "/realisations/", "target": ""},
            "service-hero-note": "Boutique livrée en 8 à 12 semaines",
            "service-benefits": [
                {"title": "WooCommerce sur mesure", "text": "Design boutique aligné sur votre marque — pas de thème Shopify limité."},
                {"title": "Tunnel de conversion", "text": "Panier, checkout et relances optimisés pour réduire l'abandon."},
                {"title": "SEO produits", "text": "Fiches produits, catégories et schema.org Product intégrés."},
                {"title": "Propriété totale", "text": "WordPress + WooCommerce : vous possédez votre boutique et vos données."},
            ],
            "service-included-eyebrow": "Boutique clé en main",
            "service-included-title": "Ce qui est inclus dans votre site e-commerce",
            "service-included-text": "De la stratégie catalogue au paiement en ligne, nous couvrons l'ensemble du projet e-commerce B2C ou B2B.",
            "service-included-price": "Sur devis",
            "service-included-price-suffix": "",
            "service-included-cta": {"title": "Estimer mon projet", "url": "#contact", "target": ""},
            "service-included-features": [
                {"text": "Design UX/UI boutique sur mesure"},
                {"text": "Catalogue produits et variations"},
                {"text": "Paiement CB (Stripe, PayPal, etc.)"},
                {"text": "Gestion stocks et commandes"},
                {"text": "Livraison et zones tarifaires"},
                {"text": "SEO fiches produits et catégories"},
                {"text": "Emails transactionnels brandés"},
                {"text": "Formation gestion boutique"},
            ],
            "service-compare-eyebrow": "WooCommerce vs Shopify",
            "service-compare-title": "Pourquoi choisir WooCommerce sur mesure ?",
            "service-compare-text": "Shopify facture des abonnements et des commissions. WooCommerce sur WordPress vous donne le contrôle total, sans commission par vente.",
            "service-compare-cta": {"title": "Discuter de mon projet", "url": "#contact", "target": ""},
            "service-compare-col1-label": "WooCommerce sur mesure",
            "service-compare-col2-label": "Shopify / SaaS",
            "service-compare-table": [
                {"label": "Commission par vente", "col1": "0%", "col2": "0,5–2%"},
                {"label": "Design", "col1": "100 % personnalisé", "col2": "Thème limité"},
                {"label": "SEO", "col1": "Contrôle total", "col2": "Contraint"},
                {"label": "Propriété des données", "col1": "Vous", "col2": "Plateforme"},
                {"label": "Coût mensuel plateforme", "col1": "Hébergement seul", "col2": "29–299€+"},
                {"label": "Évolutivité", "col1": "Illimitée (WordPress)", "col2": "Apps payantes"},
            ],
            "service-compare-note": "Idéal pour les marques qui veulent posséder leur canal de vente",
            "service-audience-eyebrow": "Profils e-commerce",
            "service-audience-title": "Quelle boutique pour votre activité ?",
            "service-audience-cards": [
                {"title": "Marque D2C", "text": "Vente directe au consommateur, storytelling de marque.", "url": "/creation-site-ecommerce-nantes/"},
                {"title": "Artisan créateur", "text": "Catalogue limité, mise en valeur produit.", "url": "/creation-site-artisan-nantes/"},
                {"title": "B2B / grossiste", "text": "Tarifs dégressifs, commandes récurrentes.", "url": "/creation-site-web-nantes/"},
                {"title": "Click & collect", "text": "Commerçant nantais, retrait en magasin.", "url": "/creation-site-restaurant-nantes/"},
            ],
            "service-projects-eyebrow": "Projets e-commerce",
            "service-projects-title": "Des boutiques conçues pour vendre.",
            "service-projects": [
                {"title": "Bag X Pro", "category": "Industrie B2B", "tags": "Catalogue · Devis en ligne", "url": "/realisations/bag-x-pro/"},
                {"title": "Be Focus", "category": "Formation", "tags": "Réservation · Paiement", "url": "/realisations/be-focus/"},
                {"title": "Maison Jaden", "category": "Lead gen B2C", "tags": "WordPress · CRM", "url": "/realisations/maison-jaden/"},
            ],
            "service-method-eyebrow": "Méthode e-commerce",
            "service-method-title": "Lancer votre boutique en 5 phases.",
            "service-method-steps": [
                {"title": "Cadrage catalogue", "text": "Produits, catégories, modes de livraison et paiement."},
                {"title": "Design boutique", "text": "Maquette fiches produit, listing, panier et checkout."},
                {"title": "Intégration WooCommerce", "text": "Catalogue, stocks, taxes, moyens de paiement."},
                {"title": "Tests commandes", "text": "Parcours complet, emails, remboursements test."},
                {"title": "Lancement & SEO", "text": "Indexation produits, Google Merchant Center si besoin."},
            ],
            "service-faq-eyebrow": "FAQ e-commerce",
            "service-faq-title": "Questions sur la création de site e-commerce à Nantes.",
            "service-faq-items": [
                {"question": "Combien coûte un site e-commerce à Nantes ?", "answer": "Entre 5 000 et 15 000 € selon le nombre de produits, les variations, les langues et les intégrations (ERP, CRM). Devis personnalisé après cadrage."},
                {"question": "WooCommerce ou Shopify : que recommandez-vous ?", "answer": "WooCommerce si vous voulez la propriété, zéro commission et un design unique. Shopify si vous voulez démarrer en 48 h avec un budget template."},
                {"question": "Quels moyens de paiement sont intégrables ?", "answer": "Stripe, PayPal, Alma (paiement fractionné), virement — selon vos besoins et votre secteur."},
                {"question": "Gérez-vous la logistique et les transporteurs ?", "answer": "Nous configurons les zones, tarifs et connecteurs (Colissimo, Mondial Relay, etc.). L'expédition reste de votre côté."},
                {"question": "Mon site e-commerce sera-t-il référencé sur Google ?", "answer": "Oui. SEO technique, fiches produits optimisées, schema.org Product et maillage interne catégories."},
                {"question": "Puis-je vendre en B2B avec tarifs dégressifs ?", "answer": "Oui. WooCommerce B2B : comptes clients, tarifs par rôle, commandes sans paiement immédiat."},
                {"question": "Quel délai pour ouvrir ma boutique ?", "answer": "8 à 12 semaines pour un catalogue standard. Projets complexes : 12 à 16 semaines."},
                {"question": "Assurez-vous la maintenance de la boutique ?", "answer": "Oui. Mises à jour WooCommerce, sécurité, sauvegardes et support via contrat maintenance."},
            ],
            "service-final-cta-title": "Lancez votre boutique en ligne à Nantes",
            "service-final-reassurance": [
                {"text": "WooCommerce sur mesure"},
                {"text": "0% commission plateforme"},
                {"text": "Devis personnalisé"},
            ],
        },
    },
    {
        "file": "creation-site-vitrine-nantes.json",
        "page": {
            "title": "Création de site vitrine à Nantes",
            "slug": "creation-site-vitrine-nantes",
            "menu_order": 14,
        },
        "seo": {
            "meta_title": "Création site vitrine Nantes — WordPress dès 350€/mois | Crescendo",
            "meta_description": "Création de site vitrine à Nantes pour artisans, PME et indépendants : WordPress sur mesure, SEO local, formulaire de devis. Maquette gratuite 48h. Location sans frais de création.",
            "focus_keyword": "création site vitrine nantes",
            "canonical": f"{BASE}/creation-site-vitrine-nantes/",
        },
        "fields": {
            "service-hero-eyebrow": "Site vitrine · Nantes",
            "service-hero-title": "Création de site vitrine à Nantes",
            "service-hero-intro": "Un site vitrine professionnel est votre meilleur commercial 24h/24. Nous créons des sites WordPress sur mesure pour présenter votre activité, rassurer vos prospects et générer des contacts — artisans, PME, professions libérales et commerçants nantais.",
            "service-hero-cta-primary": {"title": "Demander ma maquette gratuite", "url": "#contact", "target": ""},
            "service-hero-cta-secondary": {"title": "Location dès 350€/mois", "url": "/location-site-internet/", "target": ""},
            "service-hero-note": "Maquette gratuite en 48h",
            "service-benefits": [
                {"title": "Orienté conversion", "text": "Chaque page pousse à l'action : devis, appel, prise de RDV."},
                {"title": "SEO local intégré", "text": "Visible sur « votre métier + Nantes » dès la mise en ligne."},
                {"title": "Design premium", "text": "Image professionnelle qui reflète la qualité de votre travail."},
                {"title": "Administration simple", "text": "Modifiez textes et images sans compétence technique."},
            ],
            "service-included-eyebrow": "Site vitrine complet",
            "service-included-title": "Ce que contient votre site vitrine",
            "service-included-text": "5 à 15 pages structurées pour convertir : accueil, services, réalisations, à propos, contact et pages SEO locales.",
            "service-included-price": "350€",
            "service-included-price-suffix": "/mois en location",
            "service-included-cta": {"title": "Lancer mon site vitrine", "url": "#contact", "target": ""},
            "service-included-features": [
                {"text": "5 à 15 pages sur mesure"},
                {"text": "Design UX/UI personnalisé"},
                {"text": "Formulaire de contact ou devis"},
                {"text": "Galerie réalisations / portfolio"},
                {"text": "Page zone d'intervention (SEO local)"},
                {"text": "Optimisation mobile et vitesse"},
                {"text": "Balisage schema.org LocalBusiness"},
                {"text": "Formation et support inclus"},
            ],
            "service-compare-eyebrow": "Vitrine sur mesure vs Wix",
            "service-compare-title": "Pourquoi un site vitrine WordPress plutôt que Wix ?",
            "service-compare-text": "Wix semble rapide, mais limite le SEO, la vitesse et l'évolutivité. Un vitrine WordPress sur mesure est un actif durable pour votre entreprise.",
            "service-compare-cta": {"title": "Comparer avec la location", "url": "/location-site-internet/", "target": ""},
            "service-compare-col1-label": "WordPress sur mesure",
            "service-compare-col2-label": "Constructeur Wix / Outil DIY",
            "service-compare-table": [
                {"label": "SEO local", "col1": "Structure optimisée", "col2": "Limité"},
                {"label": "Vitesse de chargement", "col1": "Code léger", "col2": "Scripts lourds"},
                {"label": "Design unique", "col1": "✓", "col2": "Template partagé"},
                {"label": "Évolutivité (blog, e-commerce)", "col1": "✓", "col2": "Migration difficile"},
                {"label": "Propriété", "col1": "Vous", "col2": "Plateforme"},
                {"label": "Coût sur 3 ans", "col1": "Maîtrisé", "col2": "Abonnement cumulé"},
            ],
            "service-compare-note": "Un vitrine sur mesure se rentabilise dès les premiers clients générés",
            "service-audience-eyebrow": "Pour qui ?",
            "service-audience-title": "Le site vitrine s'adapte à votre métier.",
            "service-audience-cards": [
                {"title": "Artisan", "text": "Devis en ligne, galerie chantiers, SEO local.", "url": "/creation-site-artisan-nantes/"},
                {"title": "Avocat / expert", "text": "Crédibilité, spécialités, prise de RDV.", "url": "/creation-site-avocat-nantes/"},
                {"title": "Commerçant", "text": "Horaires, produits, click & collect.", "url": "/creation-site-restaurant-nantes/"},
                {"title": "PME industrielle", "text": "Catalogue B2B, études de cas, recrutement.", "url": "/creation-site-web-nantes/"},
            ],
            "service-projects-eyebrow": "Sites vitrine livrés",
            "service-projects-title": "Des vitrines qui génèrent des contacts.",
            "service-projects": [
                {"title": "Ludovic Géhéniaux", "category": "Artisan coloriste", "tags": "Vitrine · Booking", "url": "/realisations/ludovic-geheniaux/"},
                {"title": "Maison Jaden", "category": "Constructeur", "tags": "Vitrine · Devis · CRM", "url": "/realisations/maison-jaden/"},
                {"title": "Padam Immo", "category": "Immobilier", "tags": "Vitrine · SEO local", "url": "/realisations/padam-immo/"},
            ],
            "service-method-eyebrow": "Notre méthode",
            "service-method-title": "Votre site vitrine en 5 étapes.",
            "service-method-steps": [
                {"title": "Brief", "text": "Objectifs, cibles, concurrents et mots-clés locaux."},
                {"title": "Maquette 48h", "text": "Prototype visuel gratuit pour valider la direction."},
                {"title": "Contenus", "text": "Rédaction SEO ou reprise de vos textes existants."},
                {"title": "Développement", "text": "Intégration WordPress, formulaires, tracking."},
                {"title": "Lancement", "text": "Mise en ligne, indexation Google, formation."},
            ],
            "service-faq-eyebrow": "FAQ site vitrine",
            "service-faq-title": "Questions sur la création de site vitrine à Nantes.",
            "service-faq-items": [
                {"question": "Qu'est-ce qu'un site vitrine ?", "answer": "Un site qui présente votre activité, vos services et vos réalisations pour générer des contacts — sans vente en ligne directe."},
                {"question": "Combien de pages faut-il ?", "answer": "Entre 5 et 15 selon votre activité : accueil, services, réalisations, à propos, contact, plus des pages SEO locales par zone ou spécialité."},
                {"question": "Combien coûte un site vitrine à Nantes ?", "answer": "350 €/mois en location tout inclus, ou 3 000 à 6 000 € en achat selon le nombre de pages et le niveau de design."},
                {"question": "Puis-je ajouter un blog plus tard ?", "answer": "Oui. WordPress est conçu pour évoluer : blog, e-commerce, espace client — sans refonte complète."},
                {"question": "Mon site sera-t-il adapté mobile ?", "answer": "Oui. Design mobile first : navigation, formulaires et boutons d'appel optimisés pour smartphone."},
                {"question": "Comment générer des leads avec un vitrine ?", "answer": "Formulaire de devis visible, numéro click-to-call, preuves sociales (avis, réalisations) et SEO local pour capter les recherches « métier + Nantes »."},
                {"question": "Quelle différence avec un site e-commerce ?", "answer": "Le vitrine vise la prise de contact. L'e-commerce intègre un catalogue, un panier et un paiement en ligne."},
                {"question": "Proposez-vous la location pour un vitrine ?", "answer": "Oui, 350 €/mois sans frais de création : idéal pour démarrer sans investissement initial."},
            ],
            "service-final-cta-title": "Créez votre site vitrine professionnel à Nantes",
            "service-final-reassurance": [
                {"text": "Maquette gratuite en 48h"},
                {"text": "Location dès 350€/mois"},
                {"text": "SEO local intégré"},
            ],
        },
    },
]


def build_page(spec: dict) -> dict:
    return {
        "version": "1.0",
        "page": {**spec["page"], "status": "publish"},
        "seo": {**spec["seo"], "noindex": False},
        "fields": spec["fields"],
    }


def main() -> None:
    for spec in PAGES:
        path = OUT / spec["file"]
        path.write_text(
            json.dumps(build_page(spec), ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"Wrote {path.name}")


if __name__ == "__main__":
    main()
