#!/usr/bin/env python3
"""Generate missing secteur page JSON imports."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
BASE = "https://crescendo-studio.io"

PRICING_TABLE = [
    {"label": "Investissement initial", "col1": "0€", "col2": "3 000 – 8 000€"},
    {"label": "Mensualité", "col1": "350€", "col2": "150–250€"},
    {"label": "Création incluse", "col1": "✓", "col2": "✓"},
    {"label": "Maintenance & sécurité", "col1": "Incluse", "col2": "Sur devis"},
    {"label": "Évolutions", "col1": "Incluses", "col2": "Sur devis"},
    {"label": "Total sur 5 ans", "col1": "~21 000€", "col2": "~25 000€+"},
]

PRICING_FEATURES = [
    {"text": "Création sur mesure incluse"},
    {"text": "Hébergement premium"},
    {"text": "Maintenance & mises à jour"},
    {"text": "SEO local de base"},
    {"text": "Formulaire de contact"},
    {"text": "Support réactif"},
]

AREA_CITIES = [
    {"name": "Nantes", "url": "/agence-web-nantes/"},
    {"name": "Saint-Herblain", "url": "/agence-web-saint-herblain/"},
    {"name": "Rezé", "url": "/agence-web-reze/"},
    {"name": "Orvault", "url": "/agence-web-orvault/"},
    {"name": "Carquefou", "url": "/agence-web-carquefou/"},
    {"name": "Saint-Nazaire", "url": "/agence-web-saint-nazaire/"},
]

ALL_SECTORS_LINKS = [
    ("Artisan", "/creation-site-artisan-nantes/"),
    ("Avocat", "/creation-site-avocat-nantes/"),
    ("Restaurant", "/creation-site-restaurant-nantes/"),
    ("Immobilier", "/creation-site-immobilier-nantes/"),
    ("Startup", "/creation-site-startup-nantes/"),
    ("B2B / PME", "/creation-site-b2b-nantes/"),
]

SECTORS = [
    {
        "slug": "creation-site-startup-nantes",
        "menu_order": 25,
        "title": "Création de site web pour startups à Nantes",
        "h1": "Site web pour startup à Nantes",
        "eyebrow": "Startup · Scale-up · Nantes",
        "keyword": "site web startup nantes",
        "meta_title": "Site web startup Nantes — WordPress sur mesure | Crescendo",
        "meta_description": "Création de site internet pour startup à Nantes : landing page, pitch investisseurs, recrutement, SEO. WordPress évolutif. Maquette gratuite 48h. Location dès 350€/mois.",
        "intro": "Vous lancez ou scalez une startup à Nantes — Île de Nantes, Atlanpole, French Tech ? Nous créons des sites WordPress sur mesure qui crédibilisent votre produit, convainquent investisseurs et candidats, sans brûler votre trésorerie : location dès 350 €/mois.",
        "benefits": [
            {"title": "Time-to-market", "text": "Site MVP livré en 3 à 4 semaines pour valider votre marché."},
            {"title": "Budget maîtrisé", "text": "Location sans frais de création — trésorerie préservée pour le produit."},
            {"title": "Évolutif", "text": "Ajoutez pages produit, blog, espace recrutement sans refonte."},
            {"title": "SEO dès J1", "text": "Structure pensée pour ranker sur votre marché et votre géographie."},
        ],
        "pain_title": "Pourquoi les startups nantaises échouent en ligne",
        "pain_items": [
            {"title": "Site Wix ou template générique", "text": "Image amateur face aux investisseurs et premiers clients enterprise."},
            {"title": "Pas de page produit claire", "text": "Le visiteur ne comprend pas votre value prop en 5 secondes."},
            {"title": "Invisible sur Google", "text": "Concurrents bien référencés captent les recherches « startup + Nantes » ou métier."},
            {"title": "Dette technique future", "text": "Un MVP mal construit coûte plus cher à refondre qu'un WordPress propre dès le départ."},
        ],
        "solution_title": "Un site startup pensé pour convaincre et évoluer",
        "solution_text": "Nous concevons des sites WordPress modulaires pour les startups nantaises : homepage pitch, pages produit, social proof, espace recrutement et connexion CRM — le tout administrable par votre équipe marketing.",
        "features_title": "Ce que votre site startup doit inclure",
        "features": [
            {"title": "Homepage pitch", "text": "Proposition de valeur claire, CTA primaire, preuves sociales."},
            {"title": "Pages produit", "text": "Fonctionnalités, cas d'usage, comparatif, FAQ technique."},
            {"title": "Espace recrutement", "text": "Offres d'emploi, culture, candidature spontanée."},
            {"title": "Blog / ressources", "text": "SEO longue traîne et autorité sectorielle."},
            {"title": "Connexion CRM", "text": "Leads formulaire → HubSpot, Pipedrive ou custom."},
            {"title": "Analytics & tracking", "text": "GA4, événements conversion, heatmaps si besoin."},
        ],
        "case_title": "Exemple de réalisation tech / formation",
        "case_project": "Be Focus",
        "case_tags": "WordPress · Booking · CRM",
        "case_points": [
            {"text": "Plateforme de formation pour comédiens avec réservation en ligne"},
            {"text": "Parcours conversion optimisé mobile-first"},
            {"text": "Connexion CRM pour le suivi des inscriptions"},
        ],
        "case_url": "/realisations/be-focus/",
        "pricing_title": "Combien coûte un site web pour startup à Nantes ?",
        "faq_title": "Tout savoir sur la création de site pour startup",
        "faqs": [
            {"question": "Combien coûte un site startup à Nantes ?", "answer": "350 €/mois en location tout inclus, ou 4 000 à 10 000 € en achat selon le nombre de pages et intégrations (CRM, multilingue, espace client)."},
            {"question": "Quel délai pour un site MVP ?", "answer": "3 à 4 semaines pour une landing + pages produit. Maquette gratuite sous 48 h."},
            {"question": "Peut-on connecter HubSpot ou Pipedrive ?", "answer": "Oui. Nous intégrons votre stack existante ou développons une connexion sur mesure."},
            {"question": "La location convient-elle aux startups ?", "answer": "Oui. Zéro investissement initial, évolutions incluses — idéal avant une levée de fonds."},
            {"question": "Travaillez-vous avec les incubateurs nantais ?", "answer": "Oui. Atlanpole, French Tech Nantes, Station B — nous connaissons les contraintes time-to-market des jeunes entreprises."},
            {"question": "Le site sera-t-il multilingue ?", "answer": "Oui si nécessaire. WordPress gère FR/EN nativement pour les startups visant l'export."},
        ],
        "cta_title": "Lancez votre présence web startup à Nantes",
        "cta_text": "Maquette gratuite sous 48 h pour valider la direction avant développement.",
        "form_label": "Votre startup",
        "area_title": "Site web startup à Nantes et métropole",
    },
    {
        "slug": "creation-site-b2b-nantes",
        "menu_order": 26,
        "title": "Création de site web B2B et PME à Nantes",
        "h1": "Site web B2B et PME à Nantes",
        "eyebrow": "B2B · PME · Industrie · Nantes",
        "keyword": "site web b2b nantes",
        "meta_title": "Site web B2B Nantes — PME & industrie sur mesure | Crescendo",
        "meta_description": "Création de site internet B2B à Nantes pour PME et industrie : catalogue, devis en ligne, CRM, SEO local. WordPress sur mesure. Maquette 48h. Location 350€/mois.",
        "intro": "Votre PME ou entreprise industrielle à Nantes a besoin d'un site qui génère des leads qualifiés, pas d'une vitrine statique. Nous créons des sites WordPress B2B : catalogues produits, formulaires de devis, études de cas et connexion CRM.",
        "benefits": [
            {"title": "Leads qualifiés", "text": "Formulaires devis avec champs métier pour filtrer les prospects."},
            {"title": "Crédibilité B2B", "text": "Études de cas, certifications, références clients visibles."},
            {"title": "Catalogue en ligne", "text": "Fiches produits, fiches techniques PDF, comparatifs."},
            {"title": "CRM connecté", "text": "Chaque demande alimente votre pipeline commercial."},
        ],
        "pain_title": "Les erreurs des PME nantaises sur le web",
        "pain_items": [
            {"title": "Site brochure PDF", "text": "Un PDF téléchargeable ne convertit pas — ni ne rank sur Google."},
            {"title": "Pas de suivi des leads", "text": "Demandes perdues dans une boîte mail partagée."},
            {"title": "Image datée", "text": "Site de 2015 qui ne reflète plus votre capacité industrielle."},
            {"title": "Invisible sur les requêtes métier", "text": "Vos concurrents apparaissent sur « fournisseur X Nantes », pas vous."},
        ],
        "solution_title": "Un site B2B orienté génération de leads",
        "solution_text": "Crescendo Studio conçoit des sites WordPress pour les PME nantaises : pages par gamme produit, téléchargements techniques, témoignages clients et tunnel de conversion vers devis ou RDV commercial.",
        "features_title": "Ce que votre site B2B doit inclure",
        "features": [
            {"title": "Catalogue produits", "text": "Fiches détaillées, filtres, téléchargements PDF."},
            {"title": "Formulaire devis B2B", "text": "Volume, délai, secteur — qualification automatique."},
            {"title": "Études de cas", "text": "Projets clients avec résultats chiffrés."},
            {"title": "Pages secteurs", "text": "SEO par vertical (industrie, BTP, logistique…)."},
            {"title": "Espace recrutement", "text": "Attractivité employeur pour PME en croissance."},
            {"title": "Multilingue", "text": "Export FR/EN pour clients internationaux."},
        ],
        "case_title": "Exemple de réalisation B2B",
        "case_project": "Bag X Pro",
        "case_tags": "WordPress · Catalogue · Devis",
        "case_points": [
            {"text": "Site vitrine B2B avec catalogue produits et demande de devis"},
            {"text": "SEO local et national sur le secteur industriel"},
            {"text": "Design premium orienté conversion professionnelle"},
        ],
        "case_url": "/realisations/bag-x-pro/",
        "pricing_title": "Combien coûte un site web B2B à Nantes ?",
        "faq_title": "FAQ site web B2B et PME",
        "faqs": [
            {"question": "Combien coûte un site B2B à Nantes ?", "answer": "350 €/mois en location, ou 5 000 à 12 000 € en achat selon catalogue, langues et intégrations CRM/ERP."},
            {"question": "Peut-on connecter le site à notre ERP ?", "answer": "Oui. Nous développons des connecteurs API selon faisabilité technique."},
            {"question": "Gérez-vous les fiches produits ?", "answer": "Oui. Import CSV, administration simplifiée, filtres et recherche."},
            {"question": "Le site sera-t-il référencé sur Google ?", "answer": "Oui. SEO technique + pages par produit, secteur et zone géographique."},
            {"question": "Proposez-vous la connexion CRM ?", "answer": "Oui. Voir notre offre CRM sur mesure — HubSpot, Pipedrive ou custom."},
            {"question": "Quel délai pour une PME industrielle ?", "answer": "6 à 10 semaines selon le volume de contenus et fiches produits."},
        ],
        "cta_title": "Générez plus de leads B2B avec votre site",
        "cta_text": "Audit gratuit de votre présence en ligne et maquette sous 48 h.",
        "form_label": "Votre activité B2B",
        "area_title": "Site web B2B à Nantes et Loire-Atlantique",
    },
    {
        "slug": "creation-site-coach-nantes",
        "menu_order": 27,
        "title": "Création de site web pour coachs à Nantes",
        "h1": "Site web pour coach et consultant à Nantes",
        "eyebrow": "Coach · Consultant · Nantes",
        "keyword": "site web coach nantes",
        "meta_title": "Site web coach Nantes — RDV en ligne & SEO | Crescendo",
        "meta_description": "Création de site internet pour coach et consultant à Nantes : prise de RDV, blog, témoignages, SEO local. WordPress sur mesure. Maquette gratuite 48h.",
        "intro": "Coach sportif, coach de vie, consultant RH ou formateur indépendant à Nantes ? Votre site doit convertir les visiteurs en clients : prise de RDV en ligne, témoignages, contenu expert et référencement local intégré.",
        "benefits": [
            {"title": "Prise de RDV", "text": "Calendrier en ligne synchronisé — fini les allers-retours par email."},
            {"title": "Autorité digitale", "text": "Blog et contenus qui positionnent votre expertise sur Google."},
            {"title": "Témoignages", "text": "Social proof visible pour rassurer les prospects."},
            {"title": "Location 350€/mois", "text": "Site pro sans investissement initial lourd."},
        ],
        "pain_title": "Pourquoi les coachs nantais peinent en ligne",
        "pain_items": [
            {"title": "Profil Instagram seul", "text": "Pas de site = pas de SEO Google, dépendance aux réseaux sociaux."},
            {"title": "Pas de prise de RDV", "text": "Friction maximale : le prospect repart avant de vous contacter."},
            {"title": "Contenu faible", "text": "Pas de blog = pas de trafic organique sur vos thématiques."},
            {"title": "Image amateur", "text": "Site Wix générique qui ne reflète pas votre positionnement premium."},
        ],
        "solution_title": "Un site coach orienté conversion et crédibilité",
        "solution_text": "Nous créons des sites WordPress pour coachs et consultants nantais : parcours clair, offres packagées, booking intégré, blog SEO et pages témoignages.",
        "features_title": "Ce que votre site coach doit inclure",
        "features": [
            {"title": "Prise de RDV en ligne", "text": "Calendly, Cal.com ou booking natif WordPress."},
            {"title": "Pages offres", "text": "Coaching individuel, groupe, entreprise — tarifs clairs."},
            {"title": "Blog expert", "text": "Articles SEO sur vos thématiques pour attirer du trafic."},
            {"title": "Témoignages clients", "text": "Avis, vidéos, études de cas anonymisées."},
            {"title": "Newsletter", "text": "Capture email et nurturing automatisé."},
            {"title": "Mobile first", "text": "80 % de vos prospects vous cherchent sur smartphone."},
        ],
        "case_title": "Exemple dans l'univers formation / coaching",
        "case_project": "Be Focus",
        "case_tags": "WordPress · Booking · CRM",
        "case_points": [
            {"text": "Plateforme avec réservation et gestion des inscriptions"},
            {"text": "Parcours utilisateur optimisé pour la conversion"},
            {"text": "Design premium et performances mobile"},
        ],
        "case_url": "/realisations/be-focus/",
        "pricing_title": "Combien coûte un site web pour coach à Nantes ?",
        "faq_title": "FAQ site web coach et consultant",
        "faqs": [
            {"question": "Combien coûte un site coach à Nantes ?", "answer": "350 €/mois en location tout inclus, ou 3 000 à 6 000 € en achat selon booking, blog et nombre de pages."},
            {"question": "Puis-je prendre des RDV en ligne ?", "answer": "Oui. Intégration Calendly, Cal.com ou système natif avec paiement si besoin."},
            {"question": "Le blog est-il inclus ?", "answer": "Oui. Structure blog SEO prête à publier, formation à la rédaction incluse."},
            {"question": "Mon site sera-t-il visible sur « coach Nantes » ?", "answer": "Oui. SEO local + contenu expert sur vos thématiques."},
            {"question": "Puis-je vendre des formations en ligne ?", "answer": "Oui. Pages vente, paiement Stripe et espace membre selon votre modèle."},
            {"question": "Quel délai de livraison ?", "answer": "4 à 6 semaines. Maquette gratuite sous 48 h."},
        ],
        "cta_title": "Développez votre clientèle de coaching à Nantes",
        "cta_text": "Maquette gratuite sous 48 h pour visualiser votre future vitrine pro.",
        "form_label": "Votre spécialité",
        "area_title": "Site web coach à Nantes et métropole",
    },
    {
        "slug": "creation-site-architecte-nantes",
        "menu_order": 28,
        "title": "Création de site web pour architectes à Nantes",
        "h1": "Site web pour architecte à Nantes",
        "eyebrow": "Architecte · BET · Nantes",
        "keyword": "site web architecte nantes",
        "meta_title": "Site web architecte Nantes — Portfolio sur mesure | Crescendo",
        "meta_description": "Création de site internet pour architecte à Nantes : portfolio projets, présentation du cabinet, SEO local. WordPress premium. Maquette gratuite 48h.",
        "intro": "Architecte DPLG, bureau d'études ou paysagiste à Nantes ? Votre site est votre portfolio permanent : projets réalisés, démarche créative, équipe et formulaire de contact — design à la hauteur de vos réalisations.",
        "benefits": [
            {"title": "Portfolio visuel", "text": "Galeries haute qualité, filtres par typologie (logement, tertiaire, réhabilitation)."},
            {"title": "Image premium", "text": "Design épuré qui reflète votre exigence architecturale."},
            {"title": "SEO local", "text": "Visible sur « architecte Nantes », « extension maison Nantes »."},
            {"title": "Administration simple", "text": "Ajoutez vos projets vous-même après livraison."},
        ],
        "pain_title": "Pourquoi les cabinets d'architecture manquent de visibilité",
        "pain_items": [
            {"title": "Portfolio PDF uniquement", "text": "Les maîtres d'ouvrage comparent en ligne — vous devez être présent."},
            {"title": "Site vieillissant", "text": "Projets de 2018 en une — image non representative du cabinet actuel."},
            {"title": "Pas de SEO", "text": "Invisible sur les recherches locales pourtant qualifiées."},
            {"title": "Photos mal optimisées", "text": "Site lent = visiteur parti avant de voir vos réalisations."},
        ],
        "solution_title": "Un site architecte à la hauteur de vos projets",
        "solution_text": "Nous concevons des sites WordPress pour architectes nantais : galeries full-width, fiches projet détaillées (surface, matériaux, awards), page équipe et contact orienté appels d'offres privés.",
        "features_title": "Ce que votre site architecte doit inclure",
        "features": [
            {"title": "Portfolio filtrable", "text": "Par type : neuf, réhabilitation, tertiaire, paysage."},
            {"title": "Fiches projet", "text": "Photos, plans, surface, matériaux, prix si pertinent."},
            {"title": "Page équipe", "text": "Associés, collaborateurs, certifications Order of Architects."},
            {"title": "Démarche & valeurs", "text": "Approche RSE, bioclimatique, patrimoine."},
            {"title": "Formulaire projet", "text": "Type de projet, budget, localisation, délai."},
            {"title": "Performance images", "text": "Lazy loading, WebP — galeries rapides malgré la qualité."},
        ],
        "case_title": "Exemple de réalisation construction / architecture",
        "case_project": "Maison Jaden",
        "case_tags": "WordPress · Portfolio · SEO local",
        "case_points": [
            {"text": "Site vitrine constructeur maisons individuelles à Nantes"},
            {"text": "Galerie projets et formulaire devis connecté CRM"},
            {"text": "Référencement local sur 12 communes"},
        ],
        "case_url": "/realisations/maison-jaden/",
        "pricing_title": "Combien coûte un site web pour architecte à Nantes ?",
        "faq_title": "FAQ site web architecte",
        "faqs": [
            {"question": "Combien coûte un site architecte à Nantes ?", "answer": "350 €/mois en location, ou 4 000 à 8 000 € en achat selon volume de projets et niveau de design."},
            {"question": "Puis-je ajouter mes projets moi-même ?", "answer": "Oui. Interface simplifiée : photos, titre, description, catégorie."},
            {"question": "Les images seront-elles optimisées ?", "answer": "Oui. Compression WebP, lazy loading — site rapide malgré des galeries riches."},
            {"question": "Le site respecte-t-il l'image du métier ?", "answer": "Oui. Design épuré, typographie soignée, espaces blancs — pas de template générique."},
            {"question": "Proposez-vous le multilingue ?", "answer": "Oui. FR/EN pour cabinets avec clientèle internationale."},
            {"question": "Quel délai ?", "answer": "6 à 8 semaines selon le nombre de projets à intégrer."},
        ],
        "cta_title": "Valorisez vos projets architecturaux en ligne",
        "cta_text": "Maquette gratuite sous 48 h pour définir la direction visuelle.",
        "form_label": "Votre cabinet",
        "area_title": "Site web architecte à Nantes et métropole",
    },
    {
        "slug": "creation-site-therapeute-nantes",
        "menu_order": 29,
        "title": "Création de site web pour thérapeutes à Nantes",
        "h1": "Site web pour thérapeute et praticien à Nantes",
        "eyebrow": "Thérapeute · Santé · Bien-être · Nantes",
        "keyword": "site web thérapeute nantes",
        "meta_title": "Site web thérapeute Nantes — RDV en ligne | Crescendo",
        "meta_description": "Création de site internet pour thérapeute à Nantes : psychologue, ostéopathe, sophrologue. RDV en ligne, confidentialité, SEO local. Maquette 48h.",
        "intro": "Psychologue, ostéopathe, sophrologue, naturopathe ou praticien bien-être à Nantes ? Votre site doit inspirer confiance, respecter la confidentialité et faciliter la prise de rendez-vous — sans jargon technique ni image clinique froide.",
        "benefits": [
            {"title": "Confiance & discrétion", "text": "Design apaisant, conforme RGPD, pas de tracking invasif."},
            {"title": "RDV en ligne", "text": "Réduction des appels manqués et des créneaux vides."},
            {"title": "SEO local", "text": "Visible sur « ostéopathe Nantes », « psychologue Rezé »."},
            {"title": "Contenu pédagogique", "text": "Pages par approche thérapeutique pour rassurer avant la consultation."},
        ],
        "pain_title": "Les blocages des praticiens sur le web",
        "pain_items": [
            {"title": "Annuaire Doctolib seul", "text": "Dépendance à une plateforme — pas de contrôle sur votre image."},
            {"title": "Site froid ou daté", "text": "Ne reflète pas votre approche humaine et bienveillante."},
            {"title": "Confidentialité mal gérée", "text": "Formulaires non sécurisés, cookies non conformes RGPD."},
            {"title": "Invisible hors Doctolib", "text": "Pas de trafic Google sur vos spécialités."},
        ],
        "solution_title": "Un site thérapeute rassurant et professionnel",
        "solution_text": "Nous créons des sites WordPress pour praticiens nantais : présentation de votre approche, tarifs, prise de RDV, FAQ patient et pages SEO par spécialité et quartier.",
        "features_title": "Ce que votre site thérapeute doit inclure",
        "features": [
            {"title": "Présentation du praticien", "text": "Parcours, diplômes, approche, photo professionnelle."},
            {"title": "Prise de RDV", "text": "Doctolib embed, Cal.com ou système natif."},
            {"title": "Pages spécialités", "text": "Anxiété, stress, douleurs chroniques — SEO par motif."},
            {"title": "Tarifs & remboursement", "text": "Transparence sur honoraires et mutuelles."},
            {"title": "FAQ patients", "text": "Déroulement séance, durée, première consultation."},
            {"title": "Conformité RGPD", "text": "Politique confidentialité, consentement cookies, HTTPS."},
        ],
        "case_title": "Exemple dans l'univers bien-être / artisanat",
        "case_project": "Ludovic Géhéniaux",
        "case_tags": "WordPress · Réservation · SEO",
        "case_points": [
            {"text": "Site avec système de réservation intégré"},
            {"text": "Design premium orienté confiance client"},
            {"text": "Référencement local sur Nantes"},
        ],
        "case_url": "/realisations/ludovic-geheniaux/",
        "pricing_title": "Combien coûte un site web pour thérapeute à Nantes ?",
        "faq_title": "FAQ site web thérapeute",
        "faqs": [
            {"question": "Combien coûte un site thérapeute à Nantes ?", "answer": "350 €/mois en location, ou 3 000 à 5 000 € en achat selon RDV en ligne et nombre de pages spécialité."},
            {"question": "Puis-je garder Doctolib ?", "answer": "Oui. Nous intégrons Doctolib sur votre site tout en développant votre SEO propre."},
            {"question": "Le site est-il conforme RGPD ?", "answer": "Oui. HTTPS, politique de confidentialité, gestion cookies et formulaires sécurisés."},
            {"question": "Mon site sera-t-il visible sur Google ?", "answer": "Oui. SEO local + pages par spécialité et zone géographique."},
            {"question": "Puis-je rédiger mes contenus moi-même ?", "answer": "Oui. Formation incluse. Nous pouvons aussi rédiger des textes optimisés SEO."},
            {"question": "Quel délai de livraison ?", "answer": "4 à 6 semaines. Maquette gratuite sous 48 h."},
        ],
        "cta_title": "Développez votre patientèle avec un site professionnel",
        "cta_text": "Maquette gratuite sous 48 h — design apaisant adapté à votre pratique.",
        "form_label": "Votre spécialité",
        "area_title": "Site web thérapeute à Nantes et métropole",
    },
    {
        "slug": "creation-site-association-nantes",
        "menu_order": 30,
        "title": "Création de site web pour associations à Nantes",
        "h1": "Site web pour association à Nantes",
        "eyebrow": "Association · ONG · Nantes",
        "keyword": "site web association nantes",
        "meta_title": "Site web association Nantes — Adhésions & événements | Crescendo",
        "meta_description": "Création de site internet pour association à Nantes : adhésions en ligne, événements, appel aux dons, bénévolat. WordPress accessible. Maquette 48h.",
        "intro": "Association culturelle, sportive, humanitaire ou ONG à Nantes ? Votre site mobilise adhérents, bénévoles et donateurs : actualités, agenda, adhésion en ligne et transparence sur vos actions.",
        "benefits": [
            {"title": "Adhésion en ligne", "text": "Cotisation et renouvellement automatisés via Stripe ou HelloAsso."},
            {"title": "Agenda événements", "text": "Calendrier public, inscriptions, rappels."},
            {"title": "Appel aux dons", "text": "Pages campagne avec suivi objectif et reçu fiscal si applicable."},
            {"title": "Budget maîtrisé", "text": "Location 350 €/mois — pas de gros investissement initial pour une asso."},
        ],
        "pain_title": "Pourquoi les associations peinent en ligne",
        "pain_items": [
            {"title": "Facebook remplace le site", "text": "Algorithmes changeants — vos membres ne voient plus vos posts."},
            {"title": "Site non mis à jour", "text": "Agenda vide, actualités de 2022 — image d'abandon."},
            {"title": "Adhésion manuelle", "text": "Chèques et Excel — charge admin énorme pour les bénévoles."},
            {"title": "Pas de visibilité Google", "text": "Invisible sur « association sportive Nantes » ou votre cause."},
        ],
        "solution_title": "Un site association vivant et mobilisateur",
        "solution_text": "Nous créons des sites WordPress pour associations nantaises : gestion d'événements, adhésions, appels aux dons, galerie photos et espace bénévoles — administrables par des non-techniciens.",
        "features_title": "Ce que votre site association doit inclure",
        "features": [
            {"title": "Adhésion en ligne", "text": "Formulaire, paiement CB, carte adhérent PDF."},
            {"title": "Agenda & inscriptions", "text": "Événements, ateliers, compétitions sportives."},
            {"title": "Appel aux dons", "text": "Campagnes ponctuelles avec barre de progression."},
            {"title": "Actualités & blog", "text": "Vie de l'asso, comptes-rendus, portraits bénévoles."},
            {"title": "Galerie médias", "text": "Photos et vidéos des actions sur le terrain."},
            {"title": "Accessibilité", "text": "Site lisible pour tous, conforme bonnes pratiques a11y."},
        ],
        "case_title": "Sites associatifs et institutionnels",
        "case_project": "Gide",
        "case_tags": "WordPress · Institutionnel · Multilingue",
        "case_points": [
            {"text": "Site institutionnel avec volume de contenus structuré"},
            {"text": "Navigation claire et performances optimisées"},
            {"text": "Administration simplifiée pour équipes non techniques"},
        ],
        "case_url": "/realisations/gide/",
        "pricing_title": "Combien coûte un site web pour association à Nantes ?",
        "faq_title": "FAQ site web association",
        "faqs": [
            {"question": "Combien coûte un site association à Nantes ?", "answer": "350 €/mois en location — idéal pour les budgets associatifs. Achat : 3 000 à 6 000 € selon fonctionnalités."},
            {"question": "Proposez-vous des tarifs associatifs ?", "answer": "La location à 350 €/mois sans frais de création est déjà adaptée aux budgets associatifs."},
            {"question": "Peut-on gérer le site sans compétence technique ?", "answer": "Oui. Formation incluse — vos bénévoles publient actualités et événements facilement."},
            {"question": "Intégrez-vous HelloAsso ou Stripe ?", "answer": "Oui. Adhésions, dons et événements payants selon vos outils existants."},
            {"question": "Le site est-il accessible (handicap) ?", "answer": "Oui. Nous appliquons les bonnes pratiques d'accessibilité web (contraste, navigation clavier)."},
            {"question": "Quel délai ?", "answer": "4 à 8 semaines selon le volume de contenus à migrer."},
        ],
        "cta_title": "Donnez de la visibilité à votre association à Nantes",
        "cta_text": "Maquette gratuite sous 48 h pour structurer votre présence en ligne.",
        "form_label": "Votre association",
        "area_title": "Site web association à Nantes et métropole",
    },
]


def related_sectors(current_slug: str) -> list[dict]:
    links = []
    for title, url in ALL_SECTORS_LINKS:
        if url.replace("/", "") not in current_slug and len(links) < 6:
            links.append({"title": title, "url": url})
    extras = [
        ("Coiffeur", "/creation-site-coiffeur-nantes/"),
        ("Coach", "/creation-site-coach-nantes/"),
        ("Architecte", "/creation-site-architecte-nantes/"),
        ("Thérapeute", "/creation-site-therapeute-nantes/"),
        ("Association", "/creation-site-association-nantes/"),
    ]
    for title, url in extras:
        if len(links) >= 6:
            break
        if url not in [l["url"] for l in links] and current_slug not in url:
            links.append({"title": title, "url": url})
    return links[:6]


def build_sector(s: dict) -> dict:
    slug = s["slug"]
    return {
        "version": "1.0",
        "page": {
            "title": s["title"],
            "slug": slug,
            "status": "publish",
            "menu_order": s["menu_order"],
        },
        "seo": {
            "meta_title": s["meta_title"],
            "meta_description": s["meta_description"],
            "focus_keyword": s["keyword"],
            "canonical": f"{BASE}/{slug}/",
            "noindex": False,
        },
        "fields": {
            "secteur-hero-eyebrow": s["eyebrow"],
            "secteur-hero-title": s["h1"],
            "secteur-hero-intro": s["intro"],
            "secteur-hero-cta-primary": {"title": "Demander ma maquette gratuite", "url": "#contact", "target": ""},
            "secteur-hero-cta-secondary": {"title": "Voir nos réalisations", "url": "/realisations/", "target": ""},
            "secteur-hero-note": "Maquette gratuite en 48h",
            "secteur-benefits": s["benefits"],
            "secteur-pain-title": s["pain_title"],
            "secteur-pain-items": s["pain_items"],
            "secteur-solution-title": s["solution_title"],
            "secteur-solution-text": s["solution_text"],
            "secteur-solution-price": "350€/mois",
            "secteur-solution-price-label": "Location tout inclus · zéro frais de création",
            "secteur-solution-usps": [
                {"title": "Maquette 48h", "text": "Direction créative gratuite avant engagement."},
                {"title": "WordPress sur mesure", "text": "Design premium adapté à votre secteur."},
                {"title": "SEO local intégré", "text": "Visible sur Google dès la mise en ligne."},
            ],
            "secteur-features-title": s["features_title"],
            "secteur-features-items": s["features"],
            "secteur-case-title": s["case_title"],
            "secteur-case-project-title": s["case_project"],
            "secteur-case-project-tags": s["case_tags"],
            "secteur-case-project-points": s["case_points"],
            "secteur-case-project-url": s["case_url"],
            "secteur-pricing-title": s["pricing_title"],
            "secteur-pricing-price": "350€",
            "secteur-pricing-price-suffix": "/mois",
            "secteur-pricing-cta": {"title": "Demander ma maquette gratuite", "url": "#contact", "target": ""},
            "secteur-pricing-col1-label": "Location 350€/mois",
            "secteur-pricing-col2-label": "Achat classique",
            "secteur-pricing-features": PRICING_FEATURES,
            "secteur-pricing-table": PRICING_TABLE,
            "secteur-area-title": s["area_title"],
            "secteur-area-text": "Nous accompagnons les professionnels de Nantes et de la métropole. Chaque site est optimisé pour le référencement local de votre zone d'intervention.",
            "secteur-area-cities": AREA_CITIES,
            "secteur-area-see-all": {"title": "Voir toutes nos zones", "url": "/agence-web-nantes/", "target": ""},
            "secteur-faq-eyebrow": "Questions fréquentes",
            "secteur-faq-title": s["faq_title"],
            "secteur-faq-items": s["faqs"],
            "secteur-related-title": "Autres secteurs que nous accompagnons",
            "secteur-related-sectors": related_sectors(slug),
            "secteur-final-cta-title": s["cta_title"],
            "secteur-final-cta-text": s["cta_text"],
            "secteur-final-cta-points": [
                {"text": "Maquette personnalisée sous 48h"},
                {"text": "Formule location sans investissement initial"},
                {"text": "Accompagnement local à Nantes"},
            ],
            "secteur-final-form-job-label": s["form_label"],
            "secteur-final-reassurance": [
                {"text": "Sans engagement"},
                {"text": "Réponse sous 24h"},
                {"text": "Agence nantaise"},
            ],
        },
    }


def main() -> None:
    for s in SECTORS:
        path = OUT / f"{s['slug']}.json"
        path.write_text(json.dumps(build_sector(s), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {path.name}")


if __name__ == "__main__":
    main()
