#!/usr/bin/env python3
"""Generate missing secteur page JSON imports."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
BASE = "https://crescendo-studio.io"

PRICING_TABLE = [
    {"label": "Investissement initial", "col1": "0€", "col2": "3 000 – 8 000€"},
    {"label": "Mensualité", "col1": "350€", "col2": "150–250€"},
    {"label": "Création incluse", "col1": "✓", "col2": "✓"},
    {"label": "Maintenance & sécurité", "col1": "Incluse", "col2": "Sur devis"},
    {"label": "Évolutions", "col1": "Incluses", "col2": "Sur devis"},
    {"label": "Total sur 5 ans", "col1": "~21 000€", "col2": "~25 000€+"},
]

PRICING_FEATURES = [
    {"text": "Création sur mesure incluse"},
    {"text": "Hébergement premium"},
    {"text": "Maintenance & mises à jour"},
    {"text": "SEO local de base"},
    {"text": "Formulaire de contact"},
    {"text": "Support réactif"},
]

AREA_CITIES = [
    {"name": "Nantes", "url": "/"},
    {"name": "Saint-Herblain", "url": "/agence-web-saint-herblain/"},
    {"name": "Rezé", "url": "/agence-web-reze/"},
    {"name": "Orvault", "url": "/agence-web-orvault/"},
    {"name": "Carquefou", "url": "/agence-web-carquefou/"},
    {"name": "Saint-Nazaire", "url": "/agence-web-saint-nazaire/"},
]

ALL_SECTORS_LINKS = [
    ("Artisan", "/secteurs/creation-site-artisan-nantes/"),
    ("Plombier", "/secteurs/creation-site-plombier-nantes/"),
    ("Électricien", "/secteurs/creation-site-electricien-nantes/"),
    ("BTP", "/secteurs/creation-site-btp-nantes/"),
    ("Avocat", "/secteurs/creation-site-avocat-nantes/"),
    ("Restaurant", "/secteurs/creation-site-restaurant-nantes/"),
]

SECTORS = [
    {
        "slug": "creation-site-startup-nantes",
        "menu_order": 25,
        "title": "Création de site web pour startups à Nantes",
        "h1": "Site web pour startup à Nantes",
        "eyebrow": "Startup · Scale-up · Nantes",
        "keyword": "site web startup nantes",
        "meta_title": "Site web startup Nantes — WordPress sur mesure | Crescendo",
        "meta_description": "Création de site internet pour startup à Nantes : landing page, pitch investisseurs, recrutement, SEO. WordPress évolutif. Maquette gratuite 48h. Location dès 350€/mois.",
        "intro": "Vous lancez ou scalez une startup à Nantes — Île de Nantes, Atlanpole, French Tech ? Nous créons des sites WordPress sur mesure qui crédibilisent votre produit, convainquent investisseurs et candidats, sans brûler votre trésorerie : location dès 350 €/mois.",
        "benefits": [
            {"title": "Time-to-market", "text": "Site MVP livré en 3 à 4 semaines pour valider votre marché."},
            {"title": "Budget maîtrisé", "text": "Location sans frais de création — trésorerie préservée pour le produit."},
            {"title": "Évolutif", "text": "Ajoutez pages produit, blog, espace recrutement sans refonte."},
            {"title": "SEO dès J1", "text": "Structure pensée pour ranker sur votre marché et votre géographie."},
        ],
        "pain_title": "Pourquoi les startups nantaises échouent en ligne",
        "pain_items": [
            {"title": "Site Wix ou template générique", "text": "Image amateur face aux investisseurs et premiers clients enterprise."},
            {"title": "Pas de page produit claire", "text": "Le visiteur ne comprend pas votre value prop en 5 secondes."},
            {"title": "Invisible sur Google", "text": "Concurrents bien référencés captent les recherches « startup + Nantes » ou métier."},
            {"title": "Dette technique future", "text": "Un MVP mal construit coûte plus cher à refondre qu'un WordPress propre dès le départ."},
        ],
        "solution_title": "Un site startup pensé pour convaincre et évoluer",
        "solution_text": "Nous concevons des sites WordPress modulaires pour les startups nantaises : homepage pitch, pages produit, social proof, espace recrutement et connexion CRM — le tout administrable par votre équipe marketing.",
        "features_title": "Ce que votre site startup doit inclure",
        "features": [
            {"title": "Homepage pitch", "text": "Proposition de valeur claire, CTA primaire, preuves sociales."},
            {"title": "Pages produit", "text": "Fonctionnalités, cas d'usage, comparatif, FAQ technique."},
            {"title": "Espace recrutement", "text": "Offres d'emploi, culture, candidature spontanée."},
            {"title": "Blog / ressources", "text": "SEO longue traîne et autorité sectorielle."},
            {"title": "Connexion CRM", "text": "Leads formulaire → HubSpot, Pipedrive ou custom."},
            {"title": "Analytics & tracking", "text": "GA4, événements conversion, heatmaps si besoin."},
        ],
        "case_title": "Exemple de réalisation tech / formation",
        "case_project": "Be Focus",
        "case_tags": "WordPress · Booking · CRM",
        "case_points": [
            {"text": "Plateforme de formation pour comédiens avec réservation en ligne"},
            {"text": "Parcours conversion optimisé mobile-first"},
            {"text": "Connexion CRM pour le suivi des inscriptions"},
        ],
        "case_url": "/realisations/be-focus/",
        "pricing_title": "Combien coûte un site web pour startup à Nantes ?",
        "faq_title": "Tout savoir sur la création de site pour startup",
        "faqs": [
            {"question": "Combien coûte un site startup à Nantes ?", "answer": "350 €/mois en location tout inclus, ou 4 000 à 10 000 € en achat selon le nombre de pages et intégrations (CRM, multilingue, espace client)."},
            {"question": "Quel délai pour un site MVP ?", "answer": "3 à 4 semaines pour une landing + pages produit. Maquette gratuite sous 48 h."},
            {"question": "Peut-on connecter HubSpot ou Pipedrive ?", "answer": "Oui. Nous intégrons votre stack existante ou développons une connexion sur mesure."},
            {"question": "La location convient-elle aux startups ?", "answer": "Oui. Zéro investissement initial, évolutions incluses — idéal avant une levée de fonds."},
            {"question": "Travaillez-vous avec les incubateurs nantais ?", "answer": "Oui. Atlanpole, French Tech Nantes, Station B — nous connaissons les contraintes time-to-market des jeunes entreprises."},
            {"question": "Le site sera-t-il multilingue ?", "answer": "Oui si nécessaire. WordPress gère FR/EN nativement pour les startups visant l'export."},
        ],
        "cta_title": "Lancez votre présence web startup à Nantes",
        "cta_text": "Maquette gratuite sous 48 h pour valider la direction avant développement.",
        "form_label": "Votre startup",
        "area_title": "Site web startup à Nantes et métropole",
    },
    {
        "slug": "creation-site-b2b-nantes",
        "menu_order": 26,
        "title": "Création de site web B2B et PME à Nantes",
        "h1": "Site web B2B et PME à Nantes",
        "eyebrow": "B2B · PME · Industrie · Nantes",
        "keyword": "site web b2b nantes",
        "meta_title": "Site web B2B Nantes — PME & industrie sur mesure | Crescendo",
        "meta_description": "Création de site internet B2B à Nantes pour PME et industrie : catalogue, devis en ligne, CRM, SEO local. WordPress sur mesure. Maquette 48h. Location 350€/mois.",
        "intro": "Votre PME ou entreprise industrielle à Nantes a besoin d'un site qui génère des leads qualifiés, pas d'une vitrine statique. Nous créons des sites WordPress B2B : catalogues produits, formulaires de devis, études de cas et connexion CRM.",
        "benefits": [
            {"title": "Leads qualifiés", "text": "Formulaires devis avec champs métier pour filtrer les prospects."},
            {"title": "Crédibilité B2B", "text": "Études de cas, certifications, références clients visibles."},
            {"title": "Catalogue en ligne", "text": "Fiches produits, fiches techniques PDF, comparatifs."},
            {"title": "CRM connecté", "text": "Chaque demande alimente votre pipeline commercial."},
        ],
        "pain_title": "Les erreurs des PME nantaises sur le web",
        "pain_items": [
            {"title": "Site brochure PDF", "text": "Un PDF téléchargeable ne convertit pas — ni ne rank sur Google."},
            {"title": "Pas de suivi des leads", "text": "Demandes perdues dans une boîte mail partagée."},
            {"title": "Image datée", "text": "Site de 2015 qui ne reflète plus votre capacité industrielle."},
            {"title": "Invisible sur les requêtes métier", "text": "Vos concurrents apparaissent sur « fournisseur X Nantes », pas vous."},
        ],
        "solution_title": "Un site B2B orienté génération de leads",
        "solution_text": "Crescendo Studio conçoit des sites WordPress pour les PME nantaises : pages par gamme produit, téléchargements techniques, témoignages clients et tunnel de conversion vers devis ou RDV commercial.",
        "features_title": "Ce que votre site B2B doit inclure",
        "features": [
            {"title": "Catalogue produits", "text": "Fiches détaillées, filtres, téléchargements PDF."},
            {"title": "Formulaire devis B2B", "text": "Volume, délai, secteur — qualification automatique."},
            {"title": "Études de cas", "text": "Projets clients avec résultats chiffrés."},
            {"title": "Pages secteurs", "text": "SEO par vertical (industrie, BTP, logistique…)."},
            {"title": "Espace recrutement", "text": "Attractivité employeur pour PME en croissance."},
            {"title": "Multilingue", "text": "Export FR/EN pour clients internationaux."},
        ],
        "case_title": "Exemple de réalisation B2B",
        "case_project": "Bag X Pro",
        "case_tags": "WordPress · Catalogue · Devis",
        "case_points": [
            {"text": "Site vitrine B2B avec catalogue produits et demande de devis"},
            {"text": "SEO local et national sur le secteur industriel"},
            {"text": "Design premium orienté conversion professionnelle"},
        ],
        "case_url": "/realisations/bag-x-pro/",
        "pricing_title": "Combien coûte un site web B2B à Nantes ?",
        "faq_title": "FAQ site web B2B et PME",
        "faqs": [
            {"question": "Combien coûte un site B2B à Nantes ?", "answer": "350 €/mois en location, ou 5 000 à 12 000 € en achat selon catalogue, langues et intégrations CRM/ERP."},
            {"question": "Peut-on connecter le site à notre ERP ?", "answer": "Oui. Nous développons des connecteurs API selon faisabilité technique."},
            {"question": "Gérez-vous les fiches produits ?", "answer": "Oui. Import CSV, administration simplifiée, filtres et recherche."},
            {"question": "Le site sera-t-il référencé sur Google ?", "answer": "Oui. SEO technique + pages par produit, secteur et zone géographique."},
            {"question": "Proposez-vous la connexion CRM ?", "answer": "Oui. Voir notre offre CRM sur mesure — HubSpot, Pipedrive ou custom."},
            {"question": "Quel délai pour une PME industrielle ?", "answer": "6 à 10 semaines selon le volume de contenus et fiches produits."},
        ],
        "cta_title": "Générez plus de leads B2B avec votre site",
        "cta_text": "Audit gratuit de votre présence en ligne et maquette sous 48 h.",
        "form_label": "Votre activité B2B",
        "area_title": "Site web B2B à Nantes et Loire-Atlantique",
    },
    {
        "slug": "creation-site-coach-nantes",
        "menu_order": 27,
        "title": "Création de site web pour coachs à Nantes",
        "h1": "Site web pour coach et consultant à Nantes",
        "eyebrow": "Coach · Consultant · Nantes",
        "keyword": "site web coach nantes",
        "meta_title": "Site web coach Nantes — RDV en ligne & SEO | Crescendo",
        "meta_description": "Création de site internet pour coach et consultant à Nantes : prise de RDV, blog, témoignages, SEO local. WordPress sur mesure. Maquette gratuite 48h.",
        "intro": "Coach sportif, coach de vie, consultant RH ou formateur indépendant à Nantes ? Votre site doit convertir les visiteurs en clients : prise de RDV en ligne, témoignages, contenu expert et référencement local intégré.",
        "benefits": [
            {"title": "Prise de RDV", "text": "Calendrier en ligne synchronisé — fini les allers-retours par email."},
            {"title": "Autorité digitale", "text": "Blog et contenus qui positionnent votre expertise sur Google."},
            {"title": "Témoignages", "text": "Social proof visible pour rassurer les prospects."},
            {"title": "Location 350€/mois", "text": "Site pro sans investissement initial lourd."},
        ],
        "pain_title": "Pourquoi les coachs nantais peinent en ligne",
        "pain_items": [
            {"title": "Profil Instagram seul", "text": "Pas de site = pas de SEO Google, dépendance aux réseaux sociaux."},
            {"title": "Pas de prise de RDV", "text": "Friction maximale : le prospect repart avant de vous contacter."},
            {"title": "Contenu faible", "text": "Pas de blog = pas de trafic organique sur vos thématiques."},
            {"title": "Image amateur", "text": "Site Wix générique qui ne reflète pas votre positionnement premium."},
        ],
        "solution_title": "Un site coach orienté conversion et crédibilité",
        "solution_text": "Nous créons des sites WordPress pour coachs et consultants nantais : parcours clair, offres packagées, booking intégré, blog SEO et pages témoignages.",
        "features_title": "Ce que votre site coach doit inclure",
        "features": [
            {"title": "Prise de RDV en ligne", "text": "Calendly, Cal.com ou booking natif WordPress."},
            {"title": "Pages offres", "text": "Coaching individuel, groupe, entreprise — tarifs clairs."},
            {"title": "Blog expert", "text": "Articles SEO sur vos thématiques pour attirer du trafic."},
            {"title": "Témoignages clients", "text": "Avis, vidéos, études de cas anonymisées."},
            {"title": "Newsletter", "text": "Capture email et nurturing automatisé."},
            {"title": "Mobile first", "text": "80 % de vos prospects vous cherchent sur smartphone."},
        ],
        "case_title": "Exemple dans l'univers formation / coaching",
        "case_project": "Be Focus",
        "case_tags": "WordPress · Booking · CRM",
        "case_points": [
            {"text": "Plateforme avec réservation et gestion des inscriptions"},
            {"text": "Parcours utilisateur optimisé pour la conversion"},
            {"text": "Design premium et performances mobile"},
        ],
        "case_url": "/realisations/be-focus/",
        "pricing_title": "Combien coûte un site web pour coach à Nantes ?",
        "faq_title": "FAQ site web coach et consultant",
        "faqs": [
            {"question": "Combien coûte un site coach à Nantes ?", "answer": "350 €/mois en location tout inclus, ou 3 000 à 6 000 € en achat selon booking, blog et nombre de pages."},
            {"question": "Puis-je prendre des RDV en ligne ?", "answer": "Oui. Intégration Calendly, Cal.com ou système natif avec paiement si besoin."},
            {"question": "Le blog est-il inclus ?", "answer": "Oui. Structure blog SEO prête à publier, formation à la rédaction incluse."},
            {"question": "Mon site sera-t-il visible sur « coach Nantes » ?", "answer": "Oui. SEO local + contenu expert sur vos thématiques."},
            {"question": "Puis-je vendre des formations en ligne ?", "answer": "Oui. Pages vente, paiement Stripe et espace membre selon votre modèle."},
            {"question": "Quel délai de livraison ?", "answer": "4 à 6 semaines. Maquette gratuite sous 48 h."},
        ],
        "cta_title": "Développez votre clientèle de coaching à Nantes",
        "cta_text": "Maquette gratuite sous 48 h pour visualiser votre future vitrine pro.",
        "form_label": "Votre spécialité",
        "area_title": "Site web coach à Nantes et métropole",
    },
    {
        "slug": "creation-site-architecte-nantes",
        "menu_order": 28,
        "title": "Création de site web pour architectes à Nantes",
        "h1": "Site web pour architecte à Nantes",
        "eyebrow": "Architecte · BET · Nantes",
        "keyword": "site web architecte nantes",
        "meta_title": "Site web architecte Nantes — Portfolio sur mesure | Crescendo",
        "meta_description": "Création de site internet pour architecte à Nantes : portfolio projets, présentation du cabinet, SEO local. WordPress premium. Maquette gratuite 48h.",
        "intro": "Architecte DPLG, bureau d'études ou paysagiste à Nantes ? Votre site est votre portfolio permanent : projets réalisés, démarche créative, équipe et formulaire de contact — design à la hauteur de vos réalisations.",
        "benefits": [
            {"title": "Portfolio visuel", "text": "Galeries haute qualité, filtres par typologie (logement, tertiaire, réhabilitation)."},
            {"title": "Image premium", "text": "Design épuré qui reflète votre exigence architecturale."},
            {"title": "SEO local", "text": "Visible sur « architecte Nantes », « extension maison Nantes »."},
            {"title": "Administration simple", "text": "Ajoutez vos projets vous-même après livraison."},
        ],
        "pain_title": "Pourquoi les cabinets d'architecture manquent de visibilité",
        "pain_items": [
            {"title": "Portfolio PDF uniquement", "text": "Les maîtres d'ouvrage comparent en ligne — vous devez être présent."},
            {"title": "Site vieillissant", "text": "Projets de 2018 en une — image non representative du cabinet actuel."},
            {"title": "Pas de SEO", "text": "Invisible sur les recherches locales pourtant qualifiées."},
            {"title": "Photos mal optimisées", "text": "Site lent = visiteur parti avant de voir vos réalisations."},
        ],
        "solution_title": "Un site architecte à la hauteur de vos projets",
        "solution_text": "Nous concevons des sites WordPress pour architectes nantais : galeries full-width, fiches projet détaillées (surface, matériaux, awards), page équipe et contact orienté appels d'offres privés.",
        "features_title": "Ce que votre site architecte doit inclure",
        "features": [
            {"title": "Portfolio filtrable", "text": "Par type : neuf, réhabilitation, tertiaire, paysage."},
            {"title": "Fiches projet", "text": "Photos, plans, surface, matériaux, prix si pertinent."},
            {"title": "Page équipe", "text": "Associés, collaborateurs, certifications Order of Architects."},
            {"title": "Démarche & valeurs", "text": "Approche RSE, bioclimatique, patrimoine."},
            {"title": "Formulaire projet", "text": "Type de projet, budget, localisation, délai."},
            {"title": "Performance images", "text": "Lazy loading, WebP — galeries rapides malgré la qualité."},
        ],
        "case_title": "Exemple de réalisation construction / architecture",
        "case_project": "Maison Jaden",
        "case_tags": "WordPress · Portfolio · SEO local",
        "case_points": [
            {"text": "Site vitrine constructeur maisons individuelles à Nantes"},
            {"text": "Galerie projets et formulaire devis connecté CRM"},
            {"text": "Référencement local sur 12 communes"},
        ],
        "case_url": "/realisations/maison-jaden/",
        "pricing_title": "Combien coûte un site web pour architecte à Nantes ?",
        "faq_title": "FAQ site web architecte",
        "faqs": [
            {"question": "Combien coûte un site architecte à Nantes ?", "answer": "350 €/mois en location, ou 4 000 à 8 000 € en achat selon volume de projets et niveau de design."},
            {"question": "Puis-je ajouter mes projets moi-même ?", "answer": "Oui. Interface simplifiée : photos, titre, description, catégorie."},
            {"question": "Les images seront-elles optimisées ?", "answer": "Oui. Compression WebP, lazy loading — site rapide malgré des galeries riches."},
            {"question": "Le site respecte-t-il l'image du métier ?", "answer": "Oui. Design épuré, typographie soignée, espaces blancs — pas de template générique."},
            {"question": "Proposez-vous le multilingue ?", "answer": "Oui. FR/EN pour cabinets avec clientèle internationale."},
            {"question": "Quel délai ?", "answer": "6 à 8 semaines selon le nombre de projets à intégrer."},
        ],
        "cta_title": "Valorisez vos projets architecturaux en ligne",
        "cta_text": "Maquette gratuite sous 48 h pour définir la direction visuelle.",
        "form_label": "Votre cabinet",
        "area_title": "Site web architecte à Nantes et métropole",
    },
    {
        "slug": "creation-site-therapeute-nantes",
        "menu_order": 29,
        "title": "Création de site web pour thérapeutes à Nantes",
        "h1": "Site web pour thérapeute et praticien à Nantes",
        "eyebrow": "Thérapeute · Santé · Bien-être · Nantes",
        "keyword": "site web thérapeute nantes",
        "meta_title": "Site web thérapeute Nantes — RDV en ligne | Crescendo",
        "meta_description": "Création de site internet pour thérapeute à Nantes : psychologue, ostéopathe, sophrologue. RDV en ligne, confidentialité, SEO local. Maquette 48h.",
        "intro": "Psychologue, ostéopathe, sophrologue, naturopathe ou praticien bien-être à Nantes ? Votre site doit inspirer confiance, respecter la confidentialité et faciliter la prise de rendez-vous — sans jargon technique ni image clinique froide.",
        "benefits": [
            {"title": "Confiance & discrétion", "text": "Design apaisant, conforme RGPD, pas de tracking invasif."},
            {"title": "RDV en ligne", "text": "Réduction des appels manqués et des créneaux vides."},
            {"title": "SEO local", "text": "Visible sur « ostéopathe Nantes », « psychologue Rezé »."},
            {"title": "Contenu pédagogique", "text": "Pages par approche thérapeutique pour rassurer avant la consultation."},
        ],
        "pain_title": "Les blocages des praticiens sur le web",
        "pain_items": [
            {"title": "Annuaire Doctolib seul", "text": "Dépendance à une plateforme — pas de contrôle sur votre image."},
            {"title": "Site froid ou daté", "text": "Ne reflète pas votre approche humaine et bienveillante."},
            {"title": "Confidentialité mal gérée", "text": "Formulaires non sécurisés, cookies non conformes RGPD."},
            {"title": "Invisible hors Doctolib", "text": "Pas de trafic Google sur vos spécialités."},
        ],
        "solution_title": "Un site thérapeute rassurant et professionnel",
        "solution_text": "Nous créons des sites WordPress pour praticiens nantais : présentation de votre approche, tarifs, prise de RDV, FAQ patient et pages SEO par spécialité et quartier.",
        "features_title": "Ce que votre site thérapeute doit inclure",
        "features": [
            {"title": "Présentation du praticien", "text": "Parcours, diplômes, approche, photo professionnelle."},
            {"title": "Prise de RDV", "text": "Doctolib embed, Cal.com ou système natif."},
            {"title": "Pages spécialités", "text": "Anxiété, stress, douleurs chroniques — SEO par motif."},
            {"title": "Tarifs & remboursement", "text": "Transparence sur honoraires et mutuelles."},
            {"title": "FAQ patients", "text": "Déroulement séance, durée, première consultation."},
            {"title": "Conformité RGPD", "text": "Politique confidentialité, consentement cookies, HTTPS."},
        ],
        "case_title": "Exemple dans l'univers bien-être / artisanat",
        "case_project": "Ludovic Géhéniaux",
        "case_tags": "WordPress · Réservation · SEO",
        "case_points": [
            {"text": "Site avec système de réservation intégré"},
            {"text": "Design premium orienté confiance client"},
            {"text": "Référencement local sur Nantes"},
        ],
        "case_url": "/realisations/ludovic-geheniaux/",
        "pricing_title": "Combien coûte un site web pour thérapeute à Nantes ?",
        "faq_title": "FAQ site web thérapeute",
        "faqs": [
            {"question": "Combien coûte un site thérapeute à Nantes ?", "answer": "350 €/mois en location, ou 3 000 à 5 000 € en achat selon RDV en ligne et nombre de pages spécialité."},
            {"question": "Puis-je garder Doctolib ?", "answer": "Oui. Nous intégrons Doctolib sur votre site tout en développant votre SEO propre."},
            {"question": "Le site est-il conforme RGPD ?", "answer": "Oui. HTTPS, politique de confidentialité, gestion cookies et formulaires sécurisés."},
            {"question": "Mon site sera-t-il visible sur Google ?", "answer": "Oui. SEO local + pages par spécialité et zone géographique."},
            {"question": "Puis-je rédiger mes contenus moi-même ?", "answer": "Oui. Formation incluse. Nous pouvons aussi rédiger des textes optimisés SEO."},
            {"question": "Quel délai de livraison ?", "answer": "4 à 6 semaines. Maquette gratuite sous 48 h."},
        ],
        "cta_title": "Développez votre patientèle avec un site professionnel",
        "cta_text": "Maquette gratuite sous 48 h — design apaisant adapté à votre pratique.",
        "form_label": "Votre spécialité",
        "area_title": "Site web thérapeute à Nantes et métropole",
    },
    {
        "slug": "creation-site-association-nantes",
        "menu_order": 30,
        "title": "Création de site web pour associations à Nantes",
        "h1": "Site web pour association à Nantes",
        "eyebrow": "Association · ONG · Nantes",
        "keyword": "site web association nantes",
        "meta_title": "Site web association Nantes — Adhésions & événements | Crescendo",
        "meta_description": "Création de site internet pour association à Nantes : adhésions en ligne, événements, appel aux dons, bénévolat. WordPress accessible. Maquette 48h.",
        "intro": "Association culturelle, sportive, humanitaire ou ONG à Nantes ? Votre site mobilise adhérents, bénévoles et donateurs : actualités, agenda, adhésion en ligne et transparence sur vos actions.",
        "benefits": [
            {"title": "Adhésion en ligne", "text": "Cotisation et renouvellement automatisés via Stripe ou HelloAsso."},
            {"title": "Agenda événements", "text": "Calendrier public, inscriptions, rappels."},
            {"title": "Appel aux dons", "text": "Pages campagne avec suivi objectif et reçu fiscal si applicable."},
            {"title": "Budget maîtrisé", "text": "Location 350 €/mois — pas de gros investissement initial pour une asso."},
        ],
        "pain_title": "Pourquoi les associations peinent en ligne",
        "pain_items": [
            {"title": "Facebook remplace le site", "text": "Algorithmes changeants — vos membres ne voient plus vos posts."},
            {"title": "Site non mis à jour", "text": "Agenda vide, actualités de 2022 — image d'abandon."},
            {"title": "Adhésion manuelle", "text": "Chèques et Excel — charge admin énorme pour les bénévoles."},
            {"title": "Pas de visibilité Google", "text": "Invisible sur « association sportive Nantes » ou votre cause."},
        ],
        "solution_title": "Un site association vivant et mobilisateur",
        "solution_text": "Nous créons des sites WordPress pour associations nantaises : gestion d'événements, adhésions, appels aux dons, galerie photos et espace bénévoles — administrables par des non-techniciens.",
        "features_title": "Ce que votre site association doit inclure",
        "features": [
            {"title": "Adhésion en ligne", "text": "Formulaire, paiement CB, carte adhérent PDF."},
            {"title": "Agenda & inscriptions", "text": "Événements, ateliers, compétitions sportives."},
            {"title": "Appel aux dons", "text": "Campagnes ponctuelles avec barre de progression."},
            {"title": "Actualités & blog", "text": "Vie de l'asso, comptes-rendus, portraits bénévoles."},
            {"title": "Galerie médias", "text": "Photos et vidéos des actions sur le terrain."},
            {"title": "Accessibilité", "text": "Site lisible pour tous, conforme bonnes pratiques a11y."},
        ],
        "case_title": "Sites associatifs et institutionnels",
        "case_project": "CM&A Associés",
        "case_tags": "WordPress · Institutionnel · Multilingue",
        "case_points": [
            {"text": "Site institutionnel avec volume de contenus structuré"},
            {"text": "Navigation claire et performances optimisées"},
            {"text": "Administration simplifiée pour équipes non techniques"},
        ],
        "case_url": "/realisations/cma-associes/",
        "pricing_title": "Combien coûte un site web pour association à Nantes ?",
        "faq_title": "FAQ site web association",
        "faqs": [
            {"question": "Combien coûte un site association à Nantes ?", "answer": "350 €/mois en location — idéal pour les budgets associatifs. Achat : 3 000 à 6 000 € selon fonctionnalités."},
            {"question": "Proposez-vous des tarifs associatifs ?", "answer": "La location à 350 €/mois sans frais de création est déjà adaptée aux budgets associatifs."},
            {"question": "Peut-on gérer le site sans compétence technique ?", "answer": "Oui. Formation incluse — vos bénévoles publient actualités et événements facilement."},
            {"question": "Intégrez-vous HelloAsso ou Stripe ?", "answer": "Oui. Adhésions, dons et événements payants selon vos outils existants."},
            {"question": "Le site est-il accessible (handicap) ?", "answer": "Oui. Nous appliquons les bonnes pratiques d'accessibilité web (contraste, navigation clavier)."},
            {"question": "Quel délai ?", "answer": "4 à 8 semaines selon le volume de contenus à migrer."},
        ],
        "cta_title": "Donnez de la visibilité à votre association à Nantes",
        "cta_text": "Maquette gratuite sous 48 h pour structurer votre présence en ligne.",
        "form_label": "Votre association",
        "area_title": "Site web association à Nantes et métropole",
    },
    {
        "slug": "creation-site-btp-nantes",
        "menu_order": 31,
        "title": "Création de site web pour entreprises BTP à Nantes",
        "h1": "Site web pour entreprise BTP à Nantes",
        "eyebrow": "BTP · Gros œuvre · Second œuvre · Nantes",
        "keyword": "site web btp nantes",
        "meta_title": "Site web BTP Nantes — Devis en ligne & SEO local | Crescendo",
        "meta_description": "Création de site internet BTP à Nantes : gros œuvre, rénovation, travaux publics. Devis en ligne, galerie chantiers, SEO local. Maquette 48h. Location 350€/mois.",
        "intro": "Entreprise de gros œuvre, rénovation, travaux publics ou second œuvre à Nantes ? Votre site doit générer des demandes de devis qualifiées, valoriser vos chantiers et rassurer les maîtres d'ouvrage — avec un référencement local solide sur la métropole nantaise.",
        "benefits": [
            {"title": "Devis en ligne", "text": "Formulaire chantier avec type de travaux, budget et délai souhaité."},
            {"title": "Galerie chantiers", "text": "Photos avant/après pour prouver votre savoir-faire sur le terrain."},
            {"title": "SEO local BTP", "text": "Visible sur « entreprise BTP Nantes », « rénovation Nantes »."},
            {"title": "Location 350€/mois", "text": "Site pro sans immobiliser 8 000 € de trésorerie."},
        ],
        "pain_title": "Pourquoi les entreprises BTP perdent des chantiers en ligne",
        "pain_items": [
            {"title": "Site vitrine statique", "text": "Pas de formulaire devis — le prospect appelle un concurrent plus réactif."},
            {"title": "Chantiers invisibles", "text": "Vos réalisations ne sont pas valorisées en ligne."},
            {"title": "Référencement faible", "text": "Invisible sur les requêtes locales pourtant très qualifiées."},
            {"title": "Image datée", "text": "Site de 2016 qui ne reflète plus la taille ni la qualité de votre entreprise."},
        ],
        "solution_title": "Un site BTP orienté génération de chantiers",
        "solution_text": "Nous créons des sites WordPress pour les entreprises BTP nantaises : pages par corps de métier, certifications (RGE, Qualibat), zone d'intervention, galerie chantiers et tunnel devis optimisé mobile.",
        "features_title": "Ce que votre site BTP doit inclure",
        "features": [
            {"title": "Formulaire devis chantier", "text": "Type de travaux, surface, localisation, urgence."},
            {"title": "Galerie réalisations", "text": "Chantiers classés par typologie : neuf, rénovation, extension."},
            {"title": "Certifications & labels", "text": "RGE, Qualibat, assurances décennales visibles."},
            {"title": "Pages corps de métier", "text": "Gros œuvre, couverture, terrassement, rénovation."},
            {"title": "Zone d'intervention", "text": "SEO local Nantes + 12 communes métropole."},
            {"title": "Click-to-call mobile", "text": "Bouton appel direct pour les urgences chantier."},
        ],
        "case_title": "Exemple de réalisation BTP / construction",
        "case_project": "Maison Jaden",
        "case_tags": "WordPress · Devis · CRM · SEO local",
        "case_points": [
            {"text": "Site constructeur maisons avec tunnel de demande de devis"},
            {"text": "Pages géolocalisées sur la métropole nantaise"},
            {"text": "Leads connectés au CRM pour le suivi commercial"},
        ],
        "case_url": "/realisations/maison-jaden/",
        "pricing_title": "Combien coûte un site web BTP à Nantes ?",
        "faq_title": "FAQ site web entreprise BTP",
        "faqs": [
            {"question": "Combien coûte un site BTP à Nantes ?", "answer": "350 €/mois en location tout inclus, ou 4 000 à 9 000 € en achat selon volume de pages et intégrations CRM."},
            {"question": "Puis-je afficher mes certifications RGE ?", "answer": "Oui. Section dédiée avec logos, numéros et liens de vérification."},
            {"question": "Le site génère-t-il des demandes de devis ?", "answer": "Oui. Formulaire optimisé mobile avec champs métier pour qualifier les prospects."},
            {"question": "Gérez-vous la galerie chantiers ?", "answer": "Oui. Ajout simple de photos avant/après par vos équipes après formation."},
            {"question": "Quel délai de livraison ?", "answer": "5 à 8 semaines selon le volume de contenus. Maquette gratuite sous 48 h."},
            {"question": "Intervenez-vous sur toute la Loire-Atlantique ?", "answer": "Oui. Pages SEO par ville pour étendre votre visibilité locale."},
        ],
        "cta_title": "Développez vos chantiers avec un site BTP performant",
        "cta_text": "Maquette gratuite sous 48 h pour valider la direction avant lancement.",
        "form_label": "Votre activité BTP",
        "area_title": "Site web BTP à Nantes et métropole",
    },
    {
        "slug": "creation-site-paysagiste-nantes",
        "menu_order": 32,
        "title": "Création de site web pour paysagistes à Nantes",
        "h1": "Site web pour paysagiste à Nantes",
        "eyebrow": "Paysagiste · Jardin · Espaces verts · Nantes",
        "keyword": "site web paysagiste nantes",
        "meta_title": "Site web paysagiste Nantes — Devis jardin & SEO | Crescendo",
        "meta_description": "Création de site internet paysagiste à Nantes : création jardin, entretien, arrosage. Galerie, devis en ligne, SEO local. Maquette 48h. Location 350€/mois.",
        "intro": "Paysagiste, créateur de jardins ou entreprise d'entretien d'espaces verts à Nantes ? Votre site doit séduire par vos réalisations, faciliter les demandes de devis et vous positionner sur Google quand un particulier ou une copropriété cherche un professionnel local.",
        "benefits": [
            {"title": "Portfolio jardins", "text": "Galeries avant/après pour inspirer et rassurer."},
            {"title": "Devis en ligne", "text": "Surface, type de projet, fréquence d'entretien."},
            {"title": "SEO local", "text": "« Paysagiste Nantes », « entretien jardin Rezé »."},
            {"title": "Saisonnalité", "text": "Pages offres printemps, taille, arrosage automatique."},
        ],
        "pain_title": "Pourquoi les paysagistes manquent de visibilité en ligne",
        "pain_items": [
            {"title": "Bouche-à-oreille seul", "text": "Impossible de scaler sans présence Google locale."},
            {"title": "Photos perdues sur Instagram", "text": "Pas de site = pas de conversion SEO sur vos réalisations."},
            {"title": "Pas de devis structuré", "text": "Allers-retours email qui font fuir les prospects pressés."},
            {"title": "Site générique", "text": "Template Wix qui ne met pas en valeur la qualité de vos aménagements."},
        ],
        "solution_title": "Un site paysagiste qui vend vos créations végétales",
        "solution_text": "Nous concevons des sites WordPress pour paysagistes nantais : galeries filtrables, pages services (création, entretien, éclairage, arrosage), témoignages clients et formulaire devis géolocalisé.",
        "features_title": "Ce que votre site paysagiste doit inclure",
        "features": [
            {"title": "Galerie projets", "text": "Filtres : jardin contemporain, potager, terrasse, copropriété."},
            {"title": "Pages services", "text": "Création, entretien, élagage, arrosage automatique."},
            {"title": "Devis jardin", "text": "Surface, type de sol, budget, fréquence souhaitée."},
            {"title": "Zone d'intervention", "text": "Carte et pages SEO par commune."},
            {"title": "Avis clients", "text": "Social proof Google et témoignages intégrés."},
            {"title": "Blog conseils", "text": "Entretien saisonnier pour attirer du trafic organique."},
        ],
        "case_title": "Exemple de réalisation aménagement extérieur",
        "case_project": "Maison Jaden",
        "case_tags": "WordPress · Vitrine · SEO local",
        "case_points": [
            {"text": "Site vitrine premium avec valorisation des réalisations"},
            {"text": "Parcours devis optimisé pour la conversion mobile"},
            {"text": "Référencement local sur la métropole nantaise"},
        ],
        "case_url": "/realisations/maison-jaden/",
        "pricing_title": "Combien coûte un site web paysagiste à Nantes ?",
        "faq_title": "FAQ site web paysagiste",
        "faqs": [
            {"question": "Combien coûte un site paysagiste à Nantes ?", "answer": "350 €/mois en location, ou 3 000 à 6 000 € en achat selon galerie et nombre de pages services."},
            {"question": "Puis-je ajouter mes photos de jardins ?", "answer": "Oui. Interface simple pour publier vos réalisations par catégorie."},
            {"question": "Le site sera-t-il visible sur Google ?", "answer": "Oui. SEO local + contenu par service et par ville d'intervention."},
            {"question": "Proposez-vous un blog conseils jardin ?", "answer": "Oui. Structure blog incluse pour publier des guides saisonniers."},
            {"question": "Quel délai de livraison ?", "answer": "4 à 6 semaines. Maquette gratuite sous 48 h."},
            {"question": "Ciblez-vous aussi les copropriétés ?", "answer": "Oui. Pages et contenus dédiés aux contrats d'entretien collectifs."},
        ],
        "cta_title": "Faites fleurir votre activité paysagiste en ligne",
        "cta_text": "Maquette gratuite sous 48 h pour visualiser votre future vitrine.",
        "form_label": "Votre activité paysagiste",
        "area_title": "Site web paysagiste à Nantes et métropole",
    },
    {
        "slug": "creation-site-electricien-nantes",
        "menu_order": 33,
        "title": "Création de site web pour électriciens à Nantes",
        "h1": "Site web pour électricien à Nantes",
        "eyebrow": "Électricien · Dépannage · Nantes",
        "keyword": "site web électricien nantes",
        "meta_title": "Site web électricien Nantes — Devis & dépannage | Crescendo",
        "meta_description": "Création de site internet électricien à Nantes : dépannage, rénovation électrique, domotique. Devis en ligne, SEO local, click-to-call. Maquette 48h.",
        "intro": "Électricien, artisan électricien ou entreprise de dépannage électrique à Nantes ? Votre site doit convertir les urgences et les projets de rénovation : numéro visible, devis en ligne, certifications et référencement local sur « électricien Nantes ».",
        "benefits": [
            {"title": "Click-to-call", "text": "Bouton appel sticky pour les dépannages urgents."},
            {"title": "Devis en ligne", "text": "Type d'intervention, surface, délai souhaité."},
            {"title": "SEO local", "text": "Visible sur électricien + toutes les communes métropole."},
            {"title": "Crédibilité", "text": "Qualifications, assurances et avis clients mis en avant."},
        ],
        "pain_title": "Pourquoi les électriciens perdent des appels",
        "pain_items": [
            {"title": "Invisible sur Google", "text": "Le client appelle le premier résultat — pas vous."},
            {"title": "Pas de site mobile", "text": "80 % des urgences partent d'un smartphone."},
            {"title": "Numéro caché", "text": "Pas de click-to-call = prospect perdu en 3 secondes."},
            {"title": "Concurrence Pages Jaunes", "text": "Commissions et visibilité limitée sans site propre."},
        ],
        "solution_title": "Un site électricien pensé pour l'urgence et le devis",
        "solution_text": "Nous créons des sites WordPress pour électriciens nantais : pages dépannage, rénovation, domotique, mise aux normes, zone d'intervention et formulaire devis avec qualification automatique.",
        "features_title": "Ce que votre site électricien doit inclure",
        "features": [
            {"title": "Dépannage 7j/7", "text": "Page urgence avec click-to-call prioritaire."},
            {"title": "Rénovation électrique", "text": "Mise aux normes, tableau, VMC, bornes IRVE."},
            {"title": "Domotique", "text": "Page dédiée pour projets premium."},
            {"title": "Formulaire devis", "text": "Type logement, travaux, budget estimé."},
            {"title": "Avis Google", "text": "Social proof visible dès l'accueil."},
            {"title": "Zone d'intervention", "text": "SEO local Nantes, Rezé, Orvault, etc."},
        ],
        "case_title": "Exemple de réalisation artisan / services",
        "case_project": "Ludovic Géhéniaux",
        "case_tags": "WordPress · Réservation · SEO local",
        "case_points": [
            {"text": "Site artisan avec prise de contact optimisée mobile"},
            {"text": "Design premium orienté confiance et conversion"},
            {"text": "Référencement local sur Nantes et environs"},
        ],
        "case_url": "/realisations/ludovic-geheniaux/",
        "pricing_title": "Combien coûte un site web électricien à Nantes ?",
        "faq_title": "FAQ site web électricien",
        "faqs": [
            {"question": "Combien coûte un site électricien à Nantes ?", "answer": "350 €/mois en location tout inclus, ou 3 000 à 5 000 € en achat selon pages et fonctionnalités."},
            {"question": "Le click-to-call est-il inclus ?", "answer": "Oui. Bouton appel sticky optimisé mobile pour les dépannages."},
            {"question": "Serai-je visible sur « électricien Nantes » ?", "answer": "Oui. SEO local + pages par commune et par type d'intervention."},
            {"question": "Puis-je mettre en avant la recharge IRVE ?", "answer": "Oui. Page dédiée bornes véhicules électriques avec devis en ligne."},
            {"question": "Quel délai de livraison ?", "answer": "4 à 6 semaines. Maquette gratuite sous 48 h."},
            {"question": "La location convient-elle aux artisans solo ?", "answer": "Oui. Zéro investissement initial — idéal pour démarrer ou moderniser."},
        ],
        "cta_title": "Recevez plus d'appels et de devis électricité",
        "cta_text": "Maquette gratuite sous 48 h — site mobile-first garanti.",
        "form_label": "Votre activité électricien",
        "area_title": "Site web électricien à Nantes et métropole",
    },
    {
        "slug": "creation-site-plombier-nantes",
        "menu_order": 34,
        "title": "Création de site web pour plombiers à Nantes",
        "h1": "Site web pour plombier à Nantes",
        "eyebrow": "Plombier · Chauffagiste · Nantes",
        "keyword": "site web plombier nantes",
        "meta_title": "Site web plombier Nantes — Dépannage & devis | Crescendo",
        "meta_description": "Création de site internet plombier à Nantes : dépannage, chauffage, salle de bain. Devis en ligne, SEO local, click-to-call. Maquette 48h. Location 350€/mois.",
        "intro": "Plombier, chauffagiste ou artisan sanitaire à Nantes ? Votre site doit capter les fuites urgentes et les projets de rénovation salle de bain : visible sur Google, joignable en un clic et crédible grâce à vos avis et certifications.",
        "benefits": [
            {"title": "Urgences 24h", "text": "Click-to-call et page dépannage optimisée."},
            {"title": "Devis salle de bain", "text": "Formulaire détaillé pour projets planifiés."},
            {"title": "SEO plombier Nantes", "text": "Toutes les communes de la métropole couvertes."},
            {"title": "Label RGE visible", "text": "Crédibilité pour les aides rénovation énergétique."},
        ],
        "pain_title": "Les erreurs des plombiers sur le web",
        "pain_items": [
            {"title": "Dépendance au bouche-à-oreille", "text": "Les jeunes propriétaires cherchent d'abord sur Google."},
            {"title": "Site non mobile", "text": "Une fuite à 22h — le client appelle depuis son canapé."},
            {"title": "Pas de devis en ligne", "text": "Projet salle de bain perdu au profit d'un concurrent réactif."},
            {"title": "Avis Google non exploités", "text": "50 avis 5 étoiles invisibles sur votre site."},
        ],
        "solution_title": "Un site plombier qui convertit urgence et rénovation",
        "solution_text": "Sites WordPress pour plombiers nantais : dépannage, chauffage, salle de bain, adoucisseur, entretien chaudière — avec devis en ligne, avis clients et SEO local multi-villes.",
        "features_title": "Ce que votre site plombier doit inclure",
        "features": [
            {"title": "Page dépannage urgence", "text": "Fuite, débouchage, panne chauffe-eau — click-to-call."},
            {"title": "Rénovation salle de bain", "text": "Galerie, devis en ligne, financement si besoin."},
            {"title": "Chauffage & climatisation", "text": "Installation, entretien, pompe à chaleur."},
            {"title": "Certifications RGE", "text": "Visible pour les aides MaPrimeRénov'."},
            {"title": "Zone d'intervention", "text": "Pages SEO par ville et quartier."},
            {"title": "Avis Google intégrés", "text": "Confiance immédiate pour les nouveaux clients."},
        ],
        "case_title": "Exemple de réalisation artisan local",
        "case_project": "Ludovic Géhéniaux",
        "case_tags": "WordPress · SEO local · Contact",
        "case_points": [
            {"text": "Site vitrine artisan avec conversion mobile optimisée"},
            {"text": "Référencement local sur Nantes et la métropole"},
            {"text": "Design professionnel orienté prise de contact"},
        ],
        "case_url": "/realisations/ludovic-geheniaux/",
        "pricing_title": "Combien coûte un site web plombier à Nantes ?",
        "faq_title": "FAQ site web plombier",
        "faqs": [
            {"question": "Combien coûte un site plombier à Nantes ?", "answer": "350 €/mois en location, ou 3 000 à 5 500 € en achat selon pages et fonctionnalités devis."},
            {"question": "Le site aide-t-il pour les dépannages ?", "answer": "Oui. Click-to-call sticky et page urgence optimisée pour mobile."},
            {"question": "Puis-je cibler « plombier Rezé » ou « chauffagiste Orvault » ?", "answer": "Oui. Pages SEO par commune incluse dans notre approche locale."},
            {"question": "Affichage label RGE possible ?", "answer": "Oui. Section certifications avec logos et numéros."},
            {"question": "Quel délai ?", "answer": "4 à 6 semaines. Maquette gratuite sous 48 h."},
            {"question": "Maintenance incluse en location ?", "answer": "Oui. Mises à jour, sauvegardes, sécurité et support réactif."},
        ],
        "cta_title": "Plus de devis plomberie grâce à votre site web",
        "cta_text": "Maquette gratuite sous 48 h pour lancer votre présence locale.",
        "form_label": "Votre activité plombier",
        "area_title": "Site web plombier à Nantes et métropole",
    },
    {
        "slug": "creation-site-industrie-nantes",
        "menu_order": 35,
        "title": "Création de site web pour l'industrie à Nantes",
        "h1": "Site web pour entreprise industrielle à Nantes",
        "eyebrow": "Industrie · Manufacturing · Nantes",
        "keyword": "site web industrie nantes",
        "meta_title": "Site web industrie Nantes — Catalogue B2B & SEO | Crescendo",
        "meta_description": "Création de site internet pour industrie à Nantes : catalogue produits, devis B2B, certifications ISO. WordPress sur mesure. Maquette 48h. Location 350€/mois.",
        "intro": "PME industrielle, sous-traitant ou fabricant en Loire-Atlantique ? Votre site doit générer des demandes de devis qualifiées, présenter vos capacités de production et rassurer vos clients B2B avec certifications, références et fiches techniques.",
        "benefits": [
            {"title": "Catalogue B2B", "text": "Fiches produits, PDF techniques, filtres par gamme."},
            {"title": "Devis qualifiés", "text": "Volume, matière, délai — leads filtrés pour vos commerciaux."},
            {"title": "Crédibilité industrielle", "text": "ISO, capacités machines, références grands comptes."},
            {"title": "SEO métier", "text": "Visible sur vos requêtes techniques + géolocalisées."},
        ],
        "pain_title": "Pourquoi les industriels nantais sont invisibles en ligne",
        "pain_items": [
            {"title": "Site brochure PDF", "text": "Les acheteurs comparent en ligne avant de vous contacter."},
            {"title": "Pas de catalogue à jour", "text": "Fiches produits obsolètes ou absentes du web."},
            {"title": "Leads non qualifiés", "text": "Formulaire générique sans champs métier."},
            {"title": "Concurrence export", "text": "Concurrents étrangers mieux référencés sur vos niches."},
        ],
        "solution_title": "Un site industrie orienté acquisition B2B",
        "solution_text": "Nous développons des sites WordPress pour l'industrie nantaise : catalogue produits, pages capacités (usinage, injection, assemblage), certifications, études de cas et connexion CRM pour le suivi commercial.",
        "features_title": "Ce que votre site industriel doit inclure",
        "features": [
            {"title": "Catalogue produits", "text": "Fiches techniques, filtres, téléchargements PDF."},
            {"title": "Capacités industrielles", "text": "Parc machines, tolérances, matières traitées."},
            {"title": "Certifications", "text": "ISO 9001, ISO 14001, IATF — visibles et vérifiables."},
            {"title": "Études de cas", "text": "Projets clients avec résultats chiffrés."},
            {"title": "Devis B2B", "text": "Formulaire avec volume, délai, secteur d'application."},
            {"title": "Multilingue FR/EN", "text": "Export et clients internationaux."},
        ],
        "case_title": "Exemple de réalisation industrielle B2B",
        "case_project": "Bag X Pro",
        "case_tags": "WordPress · Catalogue · Devis B2B",
        "case_points": [
            {"text": "Site B2B avec catalogue produits et demandes de devis"},
            {"text": "SEO national et local sur le secteur industriel"},
            {"text": "Design premium orienté conversion professionnelle"},
        ],
        "case_url": "/realisations/bag-x-pro/",
        "pricing_title": "Combien coûte un site web industriel à Nantes ?",
        "faq_title": "FAQ site web industrie",
        "faqs": [
            {"question": "Combien coûte un site industrie à Nantes ?", "answer": "350 €/mois en location, ou 5 000 à 12 000 € en achat selon catalogue, langues et intégrations."},
            {"question": "Peut-on connecter le site au CRM ?", "answer": "Oui. HubSpot, Pipedrive ou CRM sur mesure — voir notre offre dédiée."},
            {"question": "Gérez-vous les fiches produits ?", "answer": "Oui. Import CSV, filtres, recherche et PDF téléchargeables."},
            {"question": "Le site sera-t-il multilingue ?", "answer": "Oui. FR/EN natif pour l'export industriel."},
            {"question": "Quel délai pour un catalogue complet ?", "answer": "8 à 12 semaines selon le volume de fiches produits."},
            {"question": "Proposez-vous des pages SEO par secteur ?", "answer": "Oui. Automotive, aéronautique, agroalimentaire, naval — selon votre cible."},
        ],
        "cta_title": "Générez des leads industriels qualifiés en ligne",
        "cta_text": "Audit gratuit et maquette sous 48 h pour cadrer votre projet B2B.",
        "form_label": "Votre secteur industriel",
        "area_title": "Site web industrie à Nantes et Loire-Atlantique",
    },
    {
        "slug": "creation-site-cabinet-rh-nantes",
        "menu_order": 36,
        "title": "Création de site web pour cabinets RH à Nantes",
        "h1": "Site web pour cabinet RH et recrutement à Nantes",
        "eyebrow": "RH · Recrutement · Conseil · Nantes",
        "keyword": "site web cabinet rh nantes",
        "meta_title": "Site web cabinet RH Nantes — Recrutement & SEO | Crescendo",
        "meta_description": "Création de site internet cabinet RH à Nantes : recrutement, coaching, audit social. Vitrine premium, offres d'emploi, SEO local. Maquette 48h.",
        "intro": "Cabinet de recrutement, conseil RH ou chasseur de têtes à Nantes ? Votre site doit crédibiliser votre expertise, présenter vos métiers couverts et convertir entreprises comme candidats — avec une image professionnelle à la hauteur de vos clients grands comptes.",
        "benefits": [
            {"title": "Image premium", "text": "Design institutionnel qui rassure DRH et candidats."},
            {"title": "Offres d'emploi", "text": "Publication et SEO des postes ouverts."},
            {"title": "Double cible", "text": "Parcours entreprises et candidats clairement séparés."},
            {"title": "SEO RH local", "text": "« Cabinet recrutement Nantes », « chasseur de têtes »."},
        ],
        "pain_title": "Pourquoi les cabinets RH manquent de leads en ligne",
        "pain_items": [
            {"title": "Site LinkedIn suffisant ?", "text": "Les DRH comparent plusieurs cabinets — vous devez avoir un site."},
            {"title": "Pas d'offres en ligne", "text": "Candidats et Google ne trouvent pas vos postes ouverts."},
            {"title": "Image générique", "text": "Template qui ne différencie pas votre expertise sectorielle."},
            {"title": "Contenu faible", "text": "Pas de pages métier — invisible sur les requêtes niche."},
        ],
        "solution_title": "Un site cabinet RH orienté crédibilité et conversion",
        "solution_text": "Nous créons des sites WordPress pour cabinets RH nantais : pages expertise (IT, industrie, cadres dirigeants), témoignages clients, offres d'emploi, blog RH et formulaires candidature/spécificaton de poste.",
        "features_title": "Ce que votre site cabinet RH doit inclure",
        "features": [
            {"title": "Pages expertise", "text": "Par secteur : IT, industrie, finance, santé."},
            {"title": "Offres d'emploi", "text": "Liste des postes, candidature en ligne, SEO job."},
            {"title": "Espace entreprises", "text": "Services recrutement, assessment, RPO."},
            {"title": "Espace candidats", "text": "Dépôt CV, alertes emploi, conseils carrière."},
            {"title": "Équipe & méthode", "text": "Consultants, process, garanties de suivi."},
            {"title": "Blog RH", "text": "Tendances marché de l'emploi nantais."},
        ],
        "case_title": "Exemple de réalisation conseil / formation",
        "case_project": "Be Focus",
        "case_tags": "WordPress · Inscriptions · CRM",
        "case_points": [
            {"text": "Plateforme avec parcours candidat/inscription optimisé"},
            {"text": "Design premium orienté conversion"},
            {"text": "Connexion CRM pour le suivi des contacts"},
        ],
        "case_url": "/realisations/be-focus/",
        "pricing_title": "Combien coûte un site web cabinet RH à Nantes ?",
        "faq_title": "FAQ site web cabinet RH",
        "faqs": [
            {"question": "Combien coûte un site cabinet RH à Nantes ?", "answer": "350 €/mois en location, ou 4 000 à 8 000 € en achat selon offres d'emploi et intégrations ATS."},
            {"question": "Peut-on publier des offres d'emploi ?", "answer": "Oui. Module offres avec SEO par poste ou intégration votre ATS."},
            {"question": "Le site cible entreprises et candidats ?", "answer": "Oui. Double parcours avec CTAs distincts dès l'accueil."},
            {"question": "Intégration LinkedIn ou Indeed possible ?", "answer": "Oui selon vos outils — nous étudions la faisabilité technique."},
            {"question": "Quel délai de livraison ?", "answer": "6 à 8 semaines. Maquette gratuite sous 48 h."},
            {"question": "Proposez-vous la rédaction de contenus RH ?", "answer": "Oui. Pages expertise et articles blog optimisés SEO sur devis."},
        ],
        "cta_title": "Renforcez la visibilité de votre cabinet RH à Nantes",
        "cta_text": "Maquette gratuite sous 48 h pour définir votre image institutionnelle.",
        "form_label": "Votre cabinet RH",
        "area_title": "Site web cabinet RH à Nantes et métropole",
    },
]


def related_sectors(current_slug: str) -> list[dict]:
    links = []
    for title, url in ALL_SECTORS_LINKS:
        if url.replace("/", "") not in current_slug and len(links) < 6:
            links.append({"title": title, "url": url})
    extras = [
        ("Plombier", "/secteurs/creation-site-plombier-nantes/"),
        ("Électricien", "/secteurs/creation-site-electricien-nantes/"),
        ("BTP", "/secteurs/creation-site-btp-nantes/"),
        ("Paysagiste", "/secteurs/creation-site-paysagiste-nantes/"),
        ("Industrie", "/secteurs/creation-site-industrie-nantes/"),
        ("Cabinet RH", "/secteurs/creation-site-cabinet-rh-nantes/"),
        ("Coiffeur", "/secteurs/creation-site-coiffeur-nantes/"),
        ("Coach", "/secteurs/creation-site-coach-nantes/"),
    ]
    for title, url in extras:
        if len(links) >= 6:
            break
        if url not in [l["url"] for l in links] and current_slug not in url:
            links.append({"title": title, "url": url})
    return links[:6]


def build_sector(s: dict) -> dict:
    slug = s["slug"]
    return {
        "version": "1.0",
        "page": {
            "title": s["title"],
            "slug": slug,
            "status": "publish",
            "menu_order": s["menu_order"],
            "parent": "secteurs",
        },
        "seo": {
            "meta_title": s["meta_title"],
            "meta_description": s["meta_description"],
            "focus_keyword": s["keyword"],
            "canonical": f"{BASE}/secteurs/{slug}/",
            "noindex": False,
        },
        "fields": {
            "secteur-hero-eyebrow": s["eyebrow"],
            "secteur-hero-title": s["h1"],
            "secteur-hero-intro": s["intro"],
            "secteur-hero-cta-primary": {"title": "Demander ma maquette gratuite", "url": "#contact", "target": ""},
            "secteur-hero-cta-secondary": {"title": "Voir nos réalisations", "url": "/realisations/", "target": ""},
            "secteur-hero-note": "Maquette gratuite en 48h",
            "secteur-benefits": s["benefits"],
            "secteur-pain-title": s["pain_title"],
            "secteur-pain-items": s["pain_items"],
            "secteur-solution-title": s["solution_title"],
            "secteur-solution-text": s["solution_text"],
            "secteur-solution-price": "350€/mois",
            "secteur-solution-price-label": "Location tout inclus · zéro frais de création",
            "secteur-solution-usps": [
                {"title": "Maquette 48h", "text": "Direction créative gratuite avant engagement."},
                {"title": "WordPress sur mesure", "text": "Design premium adapté à votre secteur."},
                {"title": "SEO local intégré", "text": "Visible sur Google dès la mise en ligne."},
            ],
            "secteur-features-title": s["features_title"],
            "secteur-features-items": s["features"],
            "secteur-case-title": s["case_title"],
            "secteur-case-project-title": s["case_project"],
            "secteur-case-project-tags": s["case_tags"],
            "secteur-case-project-points": s["case_points"],
            "secteur-case-project-url": s["case_url"],
            "secteur-pricing-title": s["pricing_title"],
            "secteur-pricing-price": "350€",
            "secteur-pricing-price-suffix": "/mois",
            "secteur-pricing-cta": {"title": "Demander ma maquette gratuite", "url": "#contact", "target": ""},
            "secteur-pricing-col1-label": "Location 350€/mois",
            "secteur-pricing-col2-label": "Achat classique",
            "secteur-pricing-features": PRICING_FEATURES,
            "secteur-pricing-table": PRICING_TABLE,
            "secteur-area-title": s["area_title"],
            "secteur-area-text": "Nous accompagnons les professionnels de Nantes et de la métropole. Chaque site est optimisé pour le référencement local de votre zone d'intervention.",
            "secteur-area-cities": AREA_CITIES,
            "secteur-area-see-all": {"title": "Voir toutes nos zones", "url": "/", "target": ""},
            "secteur-faq-eyebrow": "Questions fréquentes",
            "secteur-faq-title": s["faq_title"],
            "secteur-faq-items": s["faqs"],
            "secteur-related-title": "Autres secteurs que nous accompagnons",
            "secteur-related-sectors": related_sectors(slug),
            "secteur-final-cta-title": s["cta_title"],
            "secteur-final-cta-text": s["cta_text"],
            "secteur-final-cta-points": [
                {"text": "Maquette personnalisée sous 48h"},
                {"text": "Formule location sans investissement initial"},
                {"text": "Accompagnement local à Nantes"},
            ],
            "secteur-final-form-job-label": s["form_label"],
            "secteur-final-reassurance": [
                {"text": "Sans engagement"},
                {"text": "Réponse sous 24h"},
                {"text": "Agence nantaise"},
            ],
        },
    }


def main() -> None:
    for s in SECTORS:
        path = OUT / f"{s['slug']}.json"
        path.write_text(json.dumps(build_sector(s), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {path.name}")


if __name__ == "__main__":
    main()
